### ISSUE TITLE
Set a maximum size to images in the HTML report

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#105]
From Richard:

> Perhaps the maximum image size could be limited to reduce the amount of scrolling required. It quickly becomes a pain going through these because they are so large.

**Comment by mattgarrish** [comment]
This is especially true in IE 11, where the images are not only massive in size depending on the source but cause the table to blow out the side of the screen.

You might try changing ```max-width: 100%``` on ```td.image img``` to something like ```max-height: 10em;```. That will ensure a much smaller thumbnail view, and keeps the table respectable in IE.
