### ISSUE TITLE
Report global fail/pass in a program return code

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#113]
In the case of command line launched, the program should return a code value of 0 or 1 depending on global fail or pass.

**Comment by marisademeglio** [comment]
@laudrain where 
0 = ace completed 
1 = ace exited with execution error

or where 

0 = valid epub
1 = one or more validation errors (warnings?)

?

**Comment by laudrain** [comment]
I mean the latter, but it may conflict with execution errors.
Dos Ace returns already execution errors with return code 1?
