### ISSUE TITLE
unjustified dlitem error 

### ISSUE THREAD

**Issue by tofi86** [daisy/ace#114]
Imapct | Rule | Location | Detail
-- | -- | -- | --
serious | dlitem | `kapitel5.xhtml#epubcfi(/4/14[liste_definition1]/2/2)` | Description list item does not have a `<dl>` parent elementLearn more about Lists
serious | dlitem | `kapitel5.xhtml#epubcfi(/4/14[liste_definition1]/2/4)` | Description list item does not have a `<dl>` parent elementLearn more about Lists

and this is my HTML content:

```html
<div class="liste_definition typ1 lastInContainer" id="liste_definition1">
	<dl>
		<dt>Biber</dt>
		<dd>(Castoridae) sind höhere Säugetiere (Eutheria) und gehören zur Ordnung der Nagetiere (Rodentia).</dd>
	</dl>
</div>
```

Besides the missing but optional `<def>` element I have no clue why this HTML content is not valid.

**Comment by marisademeglio** [comment]
Interesting, looks like aXe (the underlying engine used by Ace to analyze HTML documents) reports this error when the file extension is `.xhtml` but when it's `.html`, it reports no errors. See attached for identical samples (except for the extension).
[test-dl.zip](https://github.com/daisy/ace/files/1473082/test-dl.zip)

**Comment by mattgarrish** [comment]
Yes, this a known issue. Romain and I have opened issues around xhtml handling in axe. Romain was going to talk with them last week about support, so hopefully he'll have some positive news. It's a problem with element name matching when namespaces are involved.

**Comment by rdeltour** [comment]
> Romain was going to talk with them last week about support, so hopefully he'll have some positive news

Wilco and I talked about the pending PRs, including support for DPUB ARIA roles, but we didn't tackle that one (filed in aXe as dequelabs/axe-core#581).

I'll have a look at how to fix this; we need a patch for Ace in any case.
