### ISSUE TITLE
Add further details to the report documentation

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#115]
From Avneesh:
> The current documentation just gives an overview of the output report. We should improve it further so that a person who is not an accessibility expert can also understand the report. In other words the documentation of report should also help new users in understanding basics of EPUB accessibility.

**Comment by marisademeglio** [comment]
This documentation page also has to be updated to match the latest format from https://github.com/daisy/ace/pull/118

**Comment by marisademeglio** [comment]
mention severity level definitions too

**Comment by rdeltour** [comment]
Documentation updates merged to `master`.
