### ISSUE TITLE
DL item

### ISSUE THREAD

**Issue by johnlourdusamy** [daisy/ace#116]
I have received below error message from DAISY Ace (0.5.0):
"Description list item does not have a <dl> parent element"
My xHTML coding as below:
```
<aside class="gloss_box">
<dl epub:type="glossary"><dt epub:type="glossterm" id="ch02def_15">
<dfn><b>change in quantity demanded</b></dfn></dt>
<dd epub:type="glossdef">Occurs when the price of the product changes, shown as a movement along an existing</dd>
</dl>
</aside>
```
What's wrong in above code. Also I have noticed Accessible publishing knowledge base, Lists section:
```
<dl>
   <dt>**<def>**Exchange function**</def>**</dt>
   <dd>
     Sales of the product to the various members 
     of the channel of distribution.
   </dd>
   <dt><def>Physical distribution function</def></dt>
   <dd>
     Moves the product through the exchange 
     channel, along with title and ownership.
   </dd>
   <dt><def>Marketing channel</def></dt>
   <dd>
     Sets of independent organizations involved
     in the process of making a product or 
     service available for use or consumption 
     as well as providing a payment mechanism 
     for the provider.
   </dd>
   …
</dl>
```

I think this needs to change as `<dfn>` Please advice.

**Comment by rdeltour** [comment]
Thanks for the report. This is a known issue with the underlying aXe engine, that we had also already filed here as #114.

Closing this issue as duplicate, feel free to subscribe to #114 to follow the development!

**Comment by mattgarrish** [comment]
FYI, the def markup has been fixed in the example.
