### ISSUE TITLE
Ace cannot unzip some EPUB

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#121]
Ace crashes when processing some EPUBs with following messages:

HL018125:Accessibilité laudrain$ ./ace-check.sh NouvellesOrdinaires3décembre1678
verbose: ACE cwd=/Users/laudrain/Documents/Fichiers/eBook/Accessibilité, outdir=NouvellesOrdinaires3décembre1678-ace, tmpdir=NouvellesOrdinaires3décembre1678-ace, verbose=true, silent=false, jobId=
info: Processing NouvellesOrdinaires3décembre1678.epub
verbose: Extracting EPUB
error: Failed to unzip EPUB
error: Unexpected error: invalid comment length. expected: 7. found: 0
debug: Error: invalid comment length. expected: 7. found: 0
at /usr/local/lib/node_modules/ace-core/node_modules/yauzl/index.js:116:25
at /usr/local/lib/node_modules/ace-core/node_modules/yauzl/index.js:473:5
at /usr/local/lib/node_modules/ace-core/node_modules/fd-slicer/index.js:32:7
at FSReqWrap.wrapper [as oncomplete] (fs.js:665:17)
info: Closing logs.

This epub is available here:
http://www.lectura.plus/Block/download/?id=10659

It one among several produced by a French association on old press issues:
http://www.lectura.plus/848-presse-ancienne-accessible.html

These EPUB can be unzipped and also read in Readium...

**Comment by mattgarrish** [comment]
From what I see, Ace is using yauzl to unzip, and according to this bug report it is stricter in interpreting the central directory record processing: https://github.com/thejoshwolfe/yauzl/issues/48#issuecomment-266587526

Sounds like a flaw in whatever program was used to pack the epub. I ran winrar's repair option on the archive and it worked fine after for me, so if you have a program with similar functionality you could give that route a try.

**Comment by laudrain** [comment]
Thanks @mattgarrish and @rdeltour: I'll let this know to the association producing these EPUB.
Meanwhile, if Ace could get around that if would bring the checking on a11y itself...
Should it be reported as a bug of epubcheck?

**Comment by rdeltour** [comment]
I had another look at this issue. It seems that `yauzl` (the unzipping 3d party lib used by Ace) is correct.

I'm tempted to leave it as-is, just adding a the text "(The ZIP file may be corrupt)" to be a bit more informative.

Fixing the ZIP is not trivial, and would first need to extract the right info from the thrown error. Even with that, it may well be that the ZIP is more corrupt than just having an undeclared comment length.

@mattgarrish WDYT?

@laudrain did you hear back from the publisher? I'd be interested to know more about their production process, to see if there's a flaw in their ZIP utility, or if the problem comes from somewhere else.

**Comment by laudrain** [comment]
@rdeltour As I got no news, I just sent a reminder to the publisher. 
I agree with you to consider this as a corrupted ZIP.

**Comment by rdeltour** [comment]
OK, thank you Luc!

**Comment by rdeltour** [comment]
I updated the error message in #135. Closing this issue, we can reopen if we get more similar reports and need a better mitigation strategy.

**Comment by danielweck** [comment]
Hello! FYI:
In the Readium2 "streamer" we have an abstraction layer sitting on top of 3 separate concrete zip libraries:

1) `node-stream-zip`:
https://www.npmjs.com/package/node-stream-zip
https://github.com/antelle/node-stream-zip
2) `yauzl`:
https://www.npmjs.com/package/yauzl
https://github.com/thejoshwolfe/yauzl
3) `unzipper`:
https://www.npmjs.com/package/unzipper
https://github.com/ZJONSSON/node-unzipper

Option (1) `node-stream-zip` is used in the general case (publications loaded from the local filesystem), option (2) `yauzl` is used in the specific case where we fetch files from the network via byte ranges (HTTP 206 partial requests), and option (3) `unzipper` is not actually used right now :)
We extracted basic performance metrics using `process.hrtime()` and we concluded that `node-stream-zip` was "better" in the general case.

Note that we also use `yazl` to inject files into existing archives, but that's a different use-case altogether:
https://www.npmjs.com/package/yazl
https://github.com/thejoshwolfe/yazl

Cheers, Dan
