### ISSUE TITLE
"Failed to check HTML content"

### ISSUE THREAD

**Issue by katymastrocola** [daisy/ace#122]
Hello, just downloaded ACE and getting this error in Terminal: 

> info:    Parsing EPUB
> info:    Analyzing accessibility metadata
> info:    Checking package...
> info:    Checking documents...
> error:   Unexpected error: Failed to check HTML content
> info:    Closing logs.
> Re-run Ace using the --verbose option to enable full debug logging.

Any idea what's going on here? Thanks.

**Comment by katymastrocola** [comment]
I should also add that this is only occurring for ebooks packaged using our company's tool. epubs made in eCanCrusher work fine.

**Comment by mattgarrish** [comment]
Could you add --verbose when you run the command and post the output?

**Comment by katymastrocola** [comment]
Do I add --verbose to the end of the command? I ran it once at the end of the command and once with "--verbose" after "ace" and they both produced the same error:

> verbose: Extracting EPUB
> info:    Parsing EPUB
> verbose: at location '/var/folders/31/_gs6qkw92sqc4y3v0hdw6dxrc59z4t/T/tmp-39373xWwvTlNxGuW0'
> info:    Analyzing accessibility metadata
> info:    Checking package...
> info:    Checking documents...
> verbose: - Processing titlepage.xhtml
> verbose: - Processing toc.xml
> verbose: - Processing front01.xhtml
> verbose: - Processing front02.xhtml
> debug:   Error when running HTML checks: Error: Evaluation failed: TypeError: Cannot read property 'ace' of undefined
>     at <anonymous>:4:24
>     at new Promise (<anonymous>)
>     at <anonymous>:2:16
> error:   Unexpected error: Failed to check HTML content
> debug:   Error: Failed to check HTML content
>     at /usr/local/lib/node_modules/ace-core/dist/checker/checker-chromium.js:58:13
>     at Generator.throw (<anonymous>)
>     at step (/usr/local/lib/node_modules/ace-core/dist/checker/checker-chromium.js:67:191)
>     at /usr/local/lib/node_modules/ace-core/dist/checker/checker-chromium.js:67:402
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
> info:    Closing logs.
> Re-run Ace using the --verbose option to enable full debug logging.

**Comment by mattgarrish** [comment]
No, where the switch is placed doesn't matter. It just tells ace to output a detailed report, which is necessary for debugging. It's not obvious to me what the cause is here, so I'll leave for one of the developers to follow up.

**Comment by rdeltour** [comment]
Sounds like a bug. @katymastrocola could you please share a sample EPUB so that we can try to reproduce?

**Comment by katymastrocola** [comment]
Sorry for the delay! I will be away over the holidays, but here is a sample ebook made with our tool: 
[BedtimeStoriesforBaby.epub.zip](https://github.com/daisy/ace/files/1580681/BedtimeStoriesforBaby.epub.zip)

**Comment by rdeltour** [comment]
Thanks for the file! I could reproduce the issue.
It seems to be caused by the Navigation Document having an `.xml` extension instead of the recommended `.xhtml` (reported as a warning by EpubCheck).

I'll try to see how Ace can better deal with this. In the mean time, changing the extension to `.xhtml` does the trick: I tried it and Ace ran fine. (note: it not only requires to change the file name, but also all the references in the EPUB files, OPF, ToCs, etc).

**Comment by rdeltour** [comment]
Puppeteer somehow fails to inject Ace’s scripts on an `.xml` file. It works on Content Documents with extension `.foo`, so there must be something specific to the `.xml` extension. To be further investigated...

**Comment by rdeltour** [comment]
Adding tentatively to beta 5, but this can be put off to a later version if there's no easy fix. It's not super high priority given that an `.xml` extension on Content Document should be pretty rare.

**Comment by rdeltour** [comment]
The fix will be published in the next version. Thanks again @katymastrocola for the report!

**Comment by katymastrocola** [comment]
Awesome! Thanks!

**Comment by clapierre** [comment]
Not sure if this is a result of this fix or not but I am getting a lot of
warn:    Copying document with extension '.xhtml' to a temporary '.xhtml' file…
Are these warnings really necessary?  Shouldn't this be in a verbose output.

**Comment by rdeltour** [comment]
> Not sure if this is a result of this fix or not but I am getting a lot of
> warn: Copying document with extension '.xhtml' to a temporary '.xhtml' file…
> Are these warnings really necessary? Shouldn't this be in a verbose output.

Yes, this is a consequence of this fix, but this isn't intended. I'll investigate and fix ASAP.
