### ISSUE TITLE
Limit the width of images in the HTML report

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#126]
It seems the width is not limited, so the column can be pretty big and the others may be hidden in scroll purgatory.

cc @clapierre

**Comment by marisademeglio** [comment]
@rdeltour @clapierre could you send a sample report? it's been working ok for me. right now just the height is limited to 300px but in my experiments, this scaled the width automatically.

**Comment by clapierre** [comment]
sent in email due to sensitive nature of data.
