### ISSUE TITLE
Missing line break in violation details description

### ISSUE THREAD

**Issue by SarahMagdalena** [daisy/ace#128]
Just a short note... 
there is a line break missing between some entries in the reports details list, e. g. first details entry of the rules image-alt and link-name 

![ace_070](https://user-images.githubusercontent.com/18610892/33981871-cfcd6868-e0ae-11e7-88cb-8b2eb133d289.png)
![ace_070_2](https://user-images.githubusercontent.com/18610892/33981873-d06e9a3a-e0ae-11e7-8561-8a16a441a103.png)

Best regards

**Comment by rdeltour** [comment]
Good catch, thanks for the report!

**Comment by marisademeglio** [comment]
Thanks @SarahMagdalena for the report! Do you think you could email me the report files themselves? Just zip up the whole output directory, if you don't mind, and send to marisa.demeglio@gmail.com .
