### ISSUE TITLE
presentation of headings outline affected by heading's inline elements

### ISSUE THREAD

**Issue by SarahMagdalena** [daisy/ace#129]
I just noticed, that the presentation of the headings outline in the report is affected by the heading's inline elements. 
For example: The following EPUB from gutenberg.org [https://www.gutenberg.org/ebooks/19778](https://www.gutenberg.org/ebooks/19778) uses `<a>` elements to link the headings with other content. As a result, the headings are presented as links in the headings outline, but the links don't lead anywhere...

![ace_outline](https://user-images.githubusercontent.com/18610892/33996843-b8ffc21e-e0e2-11e7-942d-f7f7d35c4aa3.png)

Probably most EPUBs don't have any Inline-Elements, but maybe it's still useful to make sure the outlines are shown uniformly?

**Comment by rdeltour** [comment]
Thanks, good catch!
