### ISSUE TITLE
Console output

### ISSUE THREAD

**Issue by MSTUTZMANN** [daisy/ace#136]
I would like to be able to get the json report directly from the output made on the console like this
call "D:\logiciels\ace\npm\ace.cmd" "%1"  | findstr /V /I /R ^info >> path2json

Could you avoid addin info: in front of the first { of the json file (see screenshot below)

![capture](https://user-images.githubusercontent.com/21174119/34301801-588ad3ae-e72e-11e7-8962-5390a99458b6.png)

**Comment by rdeltour** [comment]
This should be fixed by #131, which will be included in Beta 4. You can now use `-s` (silent = no logging) and the output will consist of the JSON report only, so you can even strip the `findstr` step.

**Comment by MSTUTZMANN** [comment]
Hello,

Do you know when the Beta 4 will be available for download, so that we can validate the enhancement ?

Regards.

Marc

De : Romain Deltour <notifications@github.com<mailto:notifications@github.com>>
Répondre à : daisy/ace <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : samedi 23 décembre 2017 à 19:34
À : daisy/ace <ace@noreply.github.com<mailto:ace@noreply.github.com>>
Cc : STUTZMANN MARC <mstutzmann@hachette-livre.fr<mailto:mstutzmann@hachette-livre.fr>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [daisy/ace] Console output (#136)


This should be fixed by #131<https://github.com/daisy/ace/pull/131>, which will be included in Beta 4. You can now use -s (silent = no logging) and the output will consist of the JSON report only, so you can even strip the findstr step.

**Comment by MSTUTZMANN** [comment]
Hello,

If we redirect the result of the console to a log file we get at the end after the last }
[32minfo[39m:    Done.

Is-it possible to avoid it ?

Regards

Marc



De : Romain Deltour <notifications@github.com<mailto:notifications@github.com>>
Répondre à : daisy/ace <reply@reply.github.com<mailto:reply@reply.github.com>>
Date : samedi 23 décembre 2017 à 19:34
À : daisy/ace <ace@noreply.github.com<mailto:ace@noreply.github.com>>
Cc : STUTZMANN MARC <mstutzmann@hachette-livre.fr<mailto:mstutzmann@hachette-livre.fr>>, Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [daisy/ace] Console output (#136)


This should be fixed by #131<https://github.com/daisy/ace/pull/131>, which will be included in Beta 4. You can now use -s (silent = no logging) and the output will consist of the JSON report only, so you can even strip the findstr step.

**Comment by rdeltour** [comment]
It's available already, but in a prerelease channel. You can install with
`npm -i g @daisy/ace@next`.

Let me know if you have any issue!
