### ISSUE TITLE
Landmark main is back as a violation

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#139]
We had this discussion about having a main element or a role "main" on one major HTML tag like section.
I thought we dismissed it as you said in issue #40 "FWIW, this rule will be deactivated anyway in the upcoming release, since it doesn't make much sense in an EPUB."
Will you maintain it?

**Comment by rdeltour** [comment]
I'm surprised, since this is tested by a regression test (see the [test data](https://github.com/daisy/ace/tree/v0.8.0/tests/data/axerule-bypass) and [test method](https://github.com/daisy/ace/blob/v0.8.0/tests/__tests__/axe-rules.test.js#L47:L50)).

Can you confirm you're running the latest version, and if yes can you provide a verbose log and input file?

**Comment by laudrain** [comment]
I do have "Generated by DAISY Ace (0.8.0)" at the beginning of the report.
Attached are a zipped  EPUB preview file, and the zipped report.json.
[9782246861737-Extrait.epub.zip](https://github.com/daisy/ace/files/1590891/9782246861737-Extrait.epub.zip)
[report.json.zip](https://github.com/daisy/ace/files/1590892/report.json.zip)

And the verbose log:
laudrain$ ./ace-check.sh 9782246861737-Extrait
verbose: ACE cwd=/Users/laudrain/Documents/Fichiers/eBook/Accessibilité, outdir=9782246861737-Extrait-ace, tmpdir=9782246861737-Extrait-ace, verbose=true, silent=false, jobId=
info:    Processing 9782246861737-Extrait.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/var/folders/56/hqt0p1wx7r5ddghfrf5z0s4rmt2z82/T/tmp-119177307L1nqBdJs'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    Checking documents...
verbose: - Processing cover.xhtml
verbose: - Processing pagetitre.xhtml
verbose: - Processing ident1-1.xhtml
verbose: - Processing ident1-2.xhtml
verbose: Converting aXe results to ace for pagetitre.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
info:    - pagetitre.xhtml: 1 issues found
verbose: - Processing ident1-3.xhtml
verbose: Converting aXe results to ace for ident1-1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-1.xhtml: 2 issues found
verbose: - Processing pre2.xhtml
verbose: Converting aXe results to ace for cover.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - cover.xhtml: 3 issues found
verbose: - Processing chap1.xhtml
verbose: Converting aXe results to ace for ident1-2.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-2.xhtml: 2 issues found
verbose: - Processing ident1.xhtml
verbose: Converting aXe results to ace for ident1-3.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-3.xhtml: 2 issues found
verbose: - Processing sommaire.xhtml
verbose: Converting aXe results to ace for ident1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
info:    - ident1.xhtml: 1 issues found
verbose: Converting aXe results to ace for pre2.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - pre2.xhtml: 3 issues found
verbose: Converting aXe results to ace for chap1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - chap1.xhtml: 11 issues found
verbose: Converting aXe results to ace for sommaire.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - sommaire.xhtml: 2 issues found
info:    Consolidating results...
info:    Copying data
info:    Saving JSON report
info:    Saving HTML report
info:    Done.

**Comment by laudrain** [comment]
Re-installed ace 0.8.0
landmark main still an issue for all HTML doc.
Can you reproduce the issue with the file I sent?

**Comment by rdeltour** [comment]
I can reproduce the issue. It comes from aXe's rule [`landmark-one-main`](https://dequeuniversity.com/rules/axe/2.6/landmark-one-main) which checks the existence of a `main` element now that the [`bypass`](https://dequeuniversity.com/rules/axe/2.6/bypass) rule has been disabled.

I'm surprised we haven't been hit by this before, but definitely adding this to the next milestone! Thank you Luc for the report.

**Comment by rdeltour** [comment]
Here's what happens: in [version 2.6.0](https://github.com/dequelabs/axe-core/releases/tag/v2.6.0) aXe changed the rule `landmark-one-main` to ensure that the document contains at least one `main` landmark. Ace references aXe 2.5.0, but not a fix version, so the tests were run with aXe 2.5.0 but a new install fetched aXe 2.6.0, hence the different behavior.

I'll fix the rule for Ace, and will now freeze the referenced aXe version to avoid this kind of mismatch.
