### ISSUE TITLE
Digital Publishing WAI-ARIA roles not supported

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#140]
Role values from Digital Publishing WAI-ARIA Module 1.0 are not supported.

**Comment by rdeltour** [comment]
They should be, since v0.6.0. See the regression test ([test data](https://github.com/daisy/ace/blob/v0.8.0/tests/data/axerule-dpubroles/EPUB/content_001.xhtml) and [test method](https://github.com/daisy/ace/blob/v0.8.0/tests/__tests__/axe-rules.test.js#L52:L55)).

Can you confirm you're running a recent version, and if yes can you provide a verbose log and input file?

**Comment by laudrain** [comment]
I have "Generated by DAISY Ace (0.8.0)" at the top of the report.
Attached is the zipped report.json.
On line 223, role "doc-cover" is rejected.

Here is the verbose log:
laudrain$ ./ace-check.sh 9782246861737
[report.json.zip](https://github.com/daisy/ace/files/1590872/report.json.zip)
verbose: ACE cwd=/Users/laudrain/Documents/Fichiers/eBook/Accessibilité, outdir=9782246861737-ace, tmpdir=9782246861737-ace, verbose=true, silent=false, jobId=
info:    Processing 9782246861737.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/var/folders/56/hqt0p1wx7r5ddghfrf5z0s4rmt2z82/T/tmp-11832ZyHg6MJ2JGC6'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    Checking documents...
verbose: - Processing cover.xhtml
verbose: - Processing pagetitre.xhtml
verbose: - Processing ident1-1.xhtml
verbose: - Processing ident1-2.xhtml
verbose: Converting aXe results to ace for pagetitre.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
info:    - pagetitre.xhtml: 1 issues found
verbose: - Processing ident1-3.xhtml
verbose: Converting aXe results to ace for ident1-1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-1.xhtml: 2 issues found
verbose: - Processing pre2.xhtml
verbose: Converting aXe results to ace for cover.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - cover.xhtml: 5 issues found
verbose: - Processing chap1.xhtml
verbose: Converting aXe results to ace for ident1-2.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-2.xhtml: 2 issues found
verbose: - Processing chap2.xhtml
verbose: Converting aXe results to ace for ident1-3.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - ident1-3.xhtml: 2 issues found
verbose: - Processing defNotesFin0.xhtml
verbose: Converting aXe results to ace for pre2.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - pre2.xhtml: 3 issues found
verbose: - Processing chap3.xhtml
verbose: Converting aXe results to ace for chap1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - chap1.xhtml: 10 issues found
verbose: - Processing defNotesFin2.xhtml
verbose: Converting aXe results to ace for chap2.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - chap2.xhtml: 54 issues found
verbose: - Processing chap4.xhtml
verbose: Converting aXe results to ace for defNotesFin0.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - defNotesFin0.xhtml: 4 issues found
verbose: - Processing appen3.xhtml
verbose: Converting aXe results to ace for defNotesFin2.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - defNotesFin2.xhtml: 19 issues found
verbose: - Processing defNotesFin4.xhtml
verbose: Converting aXe results to ace for appen3.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - appen3.xhtml: 5 issues found
verbose: - Processing appen4.xhtml
verbose: Converting aXe results to ace for defNotesFin4.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - defNotesFin4.xhtml: 1 issues found
verbose: - Processing ident1.xhtml
verbose: Converting aXe results to ace for chap4.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - chap4.xhtml: 51 issues found
verbose: - Processing sommaire.xhtml
verbose: Converting aXe results to ace for chap3.xhtml
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - chap3.xhtml: 111 issues found
verbose: Converting aXe results to ace for ident1.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
info:    - ident1.xhtml: 1 issues found
verbose: Converting aXe results to ace for appen4.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - appen4.xhtml: 3 issues found
verbose: Converting aXe results to ace for sommaire.xhtml
verbose: Couldn’t find KB key for rule 'landmark-one-main'
verbose: Couldn’t find KB key for rule 'epub-type-has-matching-role'
info:    - sommaire.xhtml: 2 issues found
info:    Consolidating results...
info:    Copying data
info:    Saving JSON report
info:    Saving HTML report
info:    Done.

**Comment by laudrain** [comment]
Re-installed ace 0.8.0
role="doc-cover" still invalid.
Can you reproduce the issue with the file I sent?

**Comment by rdeltour** [comment]
I could reproduce, thank you Luc. I will have a look ASAP.
