### ISSUE TITLE
Pass rule help attribute value from aXe

### ISSUE THREAD

**Issue by larsvoigt** [daisy/ace#146]
Hi,
Is it possible that Ace can pass the rule [help](https://github.com/dequelabs/axe-core/blob/020fd150ed0bf0702a89d19712bd38ea0c3817d8/lib/rules/image-alt.json#L12) value from aXe? It would be nice to have the description how to resolve the issue in one sentence.
Thanks a lot.

**Comment by rdeltour** [comment]
Sure, makes sense!

**Comment by larsvoigt** [comment]
Thank you @rdeltour .
