### ISSUE TITLE
HTML Report On Issues page circles appearing in Next/Previous buttons

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#147]
See attached images, tested with Chrome, FF and Safari pretty much all having the same issue, although Firefox wasn't as bad.  Look at bottom Right hand corner Prev / 1/ 2 / Next
![safari](https://user-images.githubusercontent.com/7736749/34625763-ce33bf5e-f20e-11e7-86ea-6be2aa9d86f2.png)
![chrome](https://user-images.githubusercontent.com/7736749/34625768-d21e0d90-f20e-11e7-8f6d-8b0668d5a6be.png)
![firefox](https://user-images.githubusercontent.com/7736749/34625769-d510e8d8-f20e-11e7-8e76-bbc2ded963fc.png)

**Comment by marisademeglio** [comment]
Note to self, this is a CSS issue. The pagination buttons are actually list items. It's an easy fix.
