### ISSUE TITLE
Rule `epub-type-has-matching-role` lacks some metadata

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#156]
In todays Beta 0.9.0 the Best Practices found this issue but linking to the KB was unknown.

minor | Best Practice | epub-type-has-matching-roleaXe | "undefined"xhtml/lun_9781319050764_cover.xhtml#epubcfi(/4/2)Snippet:<section xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="cover" aria-label="cover page"> | Element has no ARIA role matching its epub:typeLearn more about Unknown
-- | -- | -- | -- | --

Unknown pointed to Link: http://kb.daisy.org/publishing/

**Comment by rdeltour** [comment]
thank you Charles, good catch!
