### ISSUE TITLE
Missing HTML `title` element should not be reported as error

### ISSUE THREAD

**Issue by elmimmo** [daisy/ace#174]
Empty `<title>` element in HTML documents should not be reported as error (let alone a “serious” one) since [according to HTML](https://www.w3.org/TR/html/document-metadata.html#elementdef-head#the-head-element), as referenced from [Accessible Publishing Knowledge Base > Page Title](http://kb.daisy.org/publishing/docs/html/title.html#refs) (emphasis mine):

> The `title` element is a required child in most situations, but when a **higher-level protocol provides title information,** e.g., in the Subject line of an e-mail when HTML is used as an e-mail authoring format, **the `title` element can be omitted.**

Furthermore, the current document might not even be a full section of the book, therefore not deserving a title itself. Does any reading engine even expose it? Conversely, what could arguably be useful for the reader is either the book's title, which is present in the ebook's metadata, or the current section title, which could be derived from the TOC (Navigation Document) + spine (Package Document).

This is the error currently reported:

|Impact |Ruleset   |Rule                     |Location                                                                                                           |Details|
|-------|---|--|--|--|
|serious|WCAG 2.0 A|document-title <br/>(via aXe)|"undefined" <br/>`101.xhtml#epubcfi(/2)` <br/>Snippet: <br/>`<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es">`|Document does not have a non-empty <title> element <br/>[Learn more about Page Title](http://kb.daisy.org/publishing/docs/html/title.html)

Seen on:

*	Ace v1.0.0
*	Node v9.6.1
*	macOS 10.11.6 (15G19009)

**Comment by danielweck** [comment]
This Ace "violation" is actually reported by Deque Axe, but perhaps indeed we need an EPUB-specific overriding rule to downgrade the severity.
I am aware of few reading system implementations that do make use of the title internal to individual HTML documents, as TOC headings are usually more meaningful / useful to indicate the reading location / progression to users.

**Comment by mattgarrish** [comment]
Missing titles are also a warning in epubcheck for the reason that @clapierre notes - there is no higher level protocol providing names for each document in EPUB and the titles do get exposed, particularly in browser-based reading system where the documents are loaded in an iframe.

See https://github.com/w3c/epubcheck/issues/448

**Comment by danielweck** [comment]
Thank you Charles and Matt. Issue settled.
