### ISSUE TITLE
checker-chromium.js "Error when running HTML checks: Error: Navigation Timeout Exceeded: 30000ms exceeded"

### ISSUE THREAD

**Issue by garconvacher** [daisy/ace#176]
Hi,

I've got the same issue on Windows and Linux (same logs).
I've tested with my latest ePub... and an ePub already checked with Ace two weeks ago.
(my ePubs was epubchecked 4.0.2) 

Ace 1.0.0, Node v9.11.1, Linux 4.9.0-6-amd64
```
[info:    - txt/few_files.xhtml: No issues found]
debug:   Error when running HTML checks: Error: Navigation Timeout Exceeded: 30000ms exceeded
error:   Unexpected error: Failed to check Content Document 'txt/a_file.xhtml'
debug:   Error: Failed to check Content Document 'txt/a_file.xhtml'
    at /usr/lib/node_modules/ace-core/node_modules/@daisy/ace-core/lib/checker/checker-chromium.js:72:13
    at Generator.throw (<anonymous>)
    at step (/usr/lib/node_modules/ace-core/node_modules/@daisy/ace-core/lib/checker/checker-chromium.js:81:191)
    at /usr/lib/node_modules/ace-core/node_modules/@daisy/ace-core/lib/checker/checker-chromium.js:81:402
    at <anonymous>
info:    Closing logs.
```

Ace 1.0.0, Node v9.11.1, Windows_NT 6.1.7601*
```
[info:    - txt/few_files.xhtml: No issues found]
debug:   Error when running HTML checks: Error: Navigation Timeout Exceeded: 30000ms exceeded
error:   Unexpected error: Failed to check Content Document 'txt/a_file.xhtml'
debug:   Error: Failed to check Content Document 'txt/a_file.xhtml'
    at C:\Users\me\AppData\Roaming\npm\node_modules\ace-core\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:72:13
    at Generator.throw (<anonymous>)
    at step (C:\Users\me\AppData\Roaming\npm\node_modules\ace-core\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:81:191)
    at C:\Users\me\AppData\Roaming\npm\node_modules\ace-core\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:81:402
    at <anonymous>
info:    Closing logs.
```

*Same result on another Windows computer with Node v8.9.1.

**Comment by rdeltour** [comment]
Mmm, so the error happens with an EPUB that was processed correctly before?
I’ll try to reproduce. Would you be able to share the EPUB sample?

**Comment by garconvacher** [comment]
I can't in public due to copyright issues :)
I'll send you a PM on Twitter.

**Comment by garconvacher** [comment]
This was not an Ace issue... 
After an update everything is OK on Windows and Linux.
Perhaps related to a puppeteer issue [Timeout occurs when reusing a page. #2356](https://github.com/GoogleChrome/puppeteer/issues/2356) ?

**Comment by rdeltour** [comment]
Thanks for the update :-)
I re-open just until I double check that (since I was able to reproduce), and to remind me to look for the cause of the issue, which might be due to the way we're invoking puppeteer (and could potentially happen again).

**Comment by danielweck** [comment]
Hello, I am a contributor to the Ace App (`ace-gui`) project, which uses an alternative Electron-based Axe runner to the default Puppeteer-based one.
I fixed a similar issue that occurred randomly for some EPUBs. I would like to try the EPUB that was causing problems here. Would you be able to share it with me, please? Thanks!

**Comment by garconvacher** [comment]
Hello @danielweck !
Could you send me a PM on [Twitter](https://twitter.com/garconvacher) for sharing?

**Comment by danielweck** [comment]
I would prefer not using Twitter for this type of communication. Would you mind sending me an email at `daniel.weck@gmail.com`? Thank you very much!

**Comment by garconvacher** [comment]
Of course!

**Comment by danielweck** [comment]
Hello Ludovic, I forgot to update this issue discussion thread: I am not able to reproduce the bug with the provided EPUB. I tested Ace CLI (with the normal Puppeteer Axe runner, as well as the Electron-based one which is used by Ace App / ace-gui).

**Comment by siddoib** [comment]
@danielweck , I have got a bunch of epub having simillar issues when processed using ACE via command prompt. I have already raised a separate ticket (https://github.com/daisy/ace/issues/339) before I can see one. If you able to take a look I would be more than happy to send you one of our epubs. Thanks in advance!
