### ISSUE TITLE
EACCES: permission denied on EPUB resource checking

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/ace#189]
Ace version 1.0.0
Node version 8.7.0
MacOs 10.12.6

Hi,
I've found two EPUBs, with no EPUBcheck errors and no problems in unzipping, that crash ACE with error:
`error:   Unexpected error: EACCES: permission denied, open '/path_to_folder/data/OEBPS/images/star.jpg'`

Gregorio

**Comment by gregoriopellegrino** [comment]
Found something: images seems to be with reading-only permissions.

```
total 496
-r--------  1 greg  staff   8386 28 Mag 10:57 209-1.jpg
-r--------  1 greg  staff   7840 28 Mag 10:57 222-1.jpg
-r--------  1 greg  staff   5514 28 Mag 10:57 222-2.jpg
-r--------  1 greg  staff  28491 28 Mag 10:57 224-1.jpg
-r--------  1 greg  staff  13031 28 Mag 10:57 234-1.jpg
-r--------  1 greg  staff   8032 28 Mag 10:57 240-1.jpg
-r--------  1 greg  staff      0 28 Mag 10:57 607-1.jpg
-r--------  1 greg  staff      0 28 Mag 10:57 610-1.jpg
-r--------  1 greg  staff   6608 28 Mag 10:57 614-1.jpg
-r--------  1 greg  staff      0 28 Mag 10:57 616-1.jpg
-r--------  1 greg  staff   8899 28 Mag 10:57 65-1.jpg
-r--------  1 greg  staff   7431 28 Mag 10:57 69-1.jpg
-r--------  1 greg  staff   5487 28 Mag 10:57 78-1.jpg
-r--------  1 greg  staff   3462 28 Mag 10:57 bur.jpg
-r--------  1 greg  staff   6604 28 Mag 10:57 copyright2.jpg
-r--------  1 greg  staff  94922 28 Mag 10:57 cover.jpg
-r--------  1 greg  staff    842 28 Mag 10:57 star.jpg
-r--------  1 greg  staff  18240 28 Mag 10:57 title.jpg
```

Gregorio

**Comment by rdeltour** [comment]
Thanks for the report, I’ll try to reproduce!

**Comment by danielweck** [comment]
Hello @gregoriopellegrino I have tested many EPUBs, but have not come across this problem yet.
Have you tried reproducing the bug with the latest version of Ace? (v`1.1.1`)
https://www.npmjs.com/package/@daisy/ace
https://unpkg.com/browse/@daisy/ace@1.1.1/

Are you able/allowed to share the publication(s) that are causing the problem to occur?

**Comment by gregoriopellegrino** [comment]
I can't reproduce the problem anymore, I think it's solved.
