### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by polizoto** [daisy/ace#196]
When running `npm install -g @daisy/ace`, I get the following output:

/usr/local/bin/ace -> /usr/local/lib/node_modules/@daisy/ace/bin/ace.js
/usr/local/bin/ace-http -> /usr/local/lib/node_modules/@daisy/ace/bin/ace-http.js

> puppeteer@1.5.0 install /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r564778! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium'
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.5.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by polizoto** [comment]
`sudo npm install -g @daisy/ace --unsafe-perm=true --allow-root`

**Comment by rdeltour** [comment]
Glad you found the solution! This was also mentioned in our [troubleshooting guide](https://daisy.github.io/ace/help/troubleshooting/#i-receive-an-eaccess-error-when-trying-to-install-ace-as-a-super-user-with-sudo).
