### ISSUE TITLE
Ace version different from command line to HTML report

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#198]
Please provide the following details if possible or relevant:

- [Ace 1.0.2, Node v8.7.0, Darwin 17.7.0] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [Node v8.7.0] the version of Node used to run Ace (as returned by the `node -v` command).
- [MacOS 10.13.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [Chrome 68.0.3440.42] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

Used with --verbose, first line is:
**verbose: Ace 1.0.2, Node v8.7.0, Darwin 17.7.0**

But in the HTML report, ace version is stil 1.0.1:
**Generated by DAISY Ace (1.0.1) on 2018-7-12 15:56:14**

**Comment by rdeltour** [comment]
Doh. Good catch, thanks!

**Comment by laudrain** [comment]
Still an issue. Will it be in vNext?

**Comment by rdeltour** [comment]
> Will it be in vNext?

Yes.

**Comment by vincent-gros** [comment]
I don't know if every modules must be in the same version, but I've found:

1. 1.0.0 in: 
- ace-config: [https://github.com/daisy/ace/blob/master/packages/ace-config/package.json](ace-config/package.json)
- ace-http: [https://github.com/daisy/ace/blob/master/packages/ace-http/package.json](ace-http/package.json)

2. 1.0.1 in: 
- ace-report: [https://github.com/daisy/ace/blob/master/packages/ace-report/package.json](ace-report/package.json)
- ace-logger: [https://github.com/daisy/ace/blob/master/packages/ace-logger/package.json](ace-logger/package.json)
- ace-report-axe: [https://github.com/daisy/ace/blob/master/packages/ace-report-axe/package.json](ace-report-axe/package.json)

**Comment by danielweck** [comment]
Actually the issue is broader: CLI(s) auto-version (`meow`) + the `winston` verbose logger + Ace JSON/HTML reporting.
I am about to publish a PR. The proposed fix is to use `ace-config` as the lowest common demoninator (no-deps package, authoritative source of truth for global Ace version)

**Comment by danielweck** [comment]
PR fix: https://github.com/daisy/ace/pull/226
