### ISSUE TITLE
Image role to be found at epub:type

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#201]
Please provide the following details if possible or relevant:

[1.0.2] the version of Ace impacted by the issue (as returned by the ace -v command).
[v8.7.0] the version of Node used to run Ace (as returned by the node -v command).
[MacOS 10.3.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

Following [EPUB Structural Semantics to ARIA Roles Mapping Guide](https://idpf.github.io/epub-guides/aria-mapping/), one can find **the proper value to add in the role attribute associated with the epub:type attribute**.

Both epub:type and role attributes are supposed to be in the same HTML tag, for instance:
`<section class="sectionpp" epub:type="cover" role="doc-cover">`

In that case of cover, unfortunately the Ace report on images doesn't show the role available in the enclosing section:
```
<section class="sectionpp" epub:type="cover" role="doc-cover">
    <a id="cover">
        <img src="cover/cover.jpg" alt="Couverture" class="imgpp"/>
    </a>
</section>
```

And when instead the role is inserted in the img tag, like in:
```
<section class="sectionpp" epub:type="cover">
    <a id="cover">
        <img src="cover/cover.jpg" alt="Couverture" role="doc-cover" class="imgpp"/>
    </a>
</section>
```
Ace reports well the doc-cover role in the Images tab, but there is a violation because the "epub-type-has-matching-role" rule isn't satisfied.

**Comment by laudrain** [comment]
The [EPUB Structural Semantics to ARIA Roles Mapping Guide](https://idpf.github.io/epub-guides/epub-aria-authoring/) has been modified in March 2019, and now **epub:type="Cover" has no more match role**.
Does the existing version of Ace (1.0.2) take this in account?

**Comment by rdeltour** [comment]
> Does the existing version of Ace (1.0.2) take this in account?

No, it doesn't and it is a known bug. We intend to improve the ARIA/epub:type mapping rule very soon in the next version.

**Comment by laudrain** [comment]
@rdeltour we need this improvement to put EPUBCheck 4.2 in production.
Any calendar for vNext?

**Comment by rdeltour** [comment]
No firm date yet, but I hope to release a version fixing this rule in the coming month.
