### ISSUE TITLE
accessibilityFeature printPageNumbers not checked on page list in nav file

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#203]
Please provide the following details if possible or relevant:

[1.0.2] the version of Ace impacted by the issue (as returned by the ace -v command).
[v8.7.0] the version of Node used to run Ace (as returned by the node -v command).
[MacOS 10.3.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

If the OPF contains that metadata line:
` <meta property="schema:accessibilityFeature">printPageNumbers</meta>`
 the presence of a pageList in the nav file should be checked. If the nav file has no pageList:
`<nav epub:type="page-list" role="doc-pagelist">`
a violation should be reported.

**Comment by clapierre** [comment]
Agreed, and vice versa, if there is a pagelist in the nav doc there should be a dcsource metadata field even if the source is the digital copy in a purely digital EPUB with no print equivalent.

**Comment by laudrain** [comment]
Ace already checks nav page list against dc:source. And it is good!
But do you mean that for a purely digital EPUB, there should be a pageList with a dc:source?
What would then be the dc:source ISBN ?

**Comment by clapierre** [comment]
I was told it would be the ISBN of itself in this case where they add in page #'s in the digitally born EPUB with no print equivalent.

**Comment by laudrain** [comment]
Be it purely digital or not, pageList existence should be checked, especially when metadata printPageNumbers is setup
In OPF. 
Why not always check the presence of a padeList in any case?
