### ISSUE TITLE
dc:source value should be different from the EPUB id

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#204]
Please provide the following details if possible or relevant:

[1.0.2] the version of Ace impacted by the issue (as returned by the ace -v command).
[v8.7.0] the version of Node used to run Ace (as returned by the node -v command).
[MacOS 10.3.6] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

When an EPUB has a pageLis in the nav file, Ace checks if a dc:source value in present in the OPF metadata. The value of dc:source identifies "a statically-paginated source, such as a print edition".

But if the value in dc:source is the same as the EPUB ID, Ace doesn't report any violation.

**Comment by mattgarrish** [comment]
What came up during the creation of the specification is that there are publishers who insert page numbers in purely digital works. In these cases, there isn't a print equivalent, but if we require the source to be different then the publisher is stuck in the opposite bind (i.e., what do they insert to avoid an error). To address this problem, the guidance is to self-reference in these cases.

**Comment by laudrain** [comment]
@mattgarrish coming back to this, I'm ok with self-reference for purely digital works.
So I think I can close this issue.
