### ISSUE TITLE
aria-describedby attribute can be a list of ids, not just a single id

### ISSUE THREAD

**Issue by StephenMcConnel** [daisy/ace#209]
Please provide the following details if possible or relevant:

Ace 1.0.2
Node 8.11.4
Linux 4.4.0-134-generic (Ubuntu 16.04)
debug: Error when running HTML checks: Error: Evaluation failed: TypeError: Cannot read property 'innerText' of null 
no - [] if the issue is about the HTML report: the browser(s) and version(s) you used.
yes - [] if possible, let us know if you can share a sample input file to help us reproduce the issue.
[aceoutput.txt](https://github.com/daisy/ace/files/2354680/aceoutput.txt)
[TestBook.epub.zip](https://github.com/daisy/ace/files/2354681/TestBook.epub.zip)

**Comment by rdeltour** [comment]
Thanks for the report! I will try to have a look and reproduce the issue.
