### ISSUE TITLE
Question - Localization for messages

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace#216]
Hi there.

Is there any initiative regarding translation for other languages?
I would like to help this project by translating its messages to pt_BR.

**Comment by rdeltour** [comment]
yes, in fact we plan to work on localization in the first half of 2019.  We’ll definitely get in touch whenever the localization framework is in place, thank you very much for the offer! 👍

See also #83.

**Comment by thiagoeec** [comment]
Any news on this subject?

**Comment by danielweck** [comment]
The current (released) version of Ace is now localized.
I am going to create a short Markdown page to explain how to translate label.
In the meantime, here are the files (3 separate Ace-related packages have their own language resources): 
https://github.com/daisy/ace/tree/master/packages/ace-core/src/l10n/locales
https://github.com/daisy/ace/tree/master/packages/ace-report-axe/src/l10n/locales
https://github.com/daisy/ace/tree/master/packages/ace-report/src/l10n/locales

**Comment by danielweck** [comment]
Wiki page:
https://github.com/daisy/ace/wiki/Localization

**Comment by danielweck** [comment]
Note that the Ace "app" (GUI) has its own localization resources, based on the exact same technical underpinning as Ace (core). See:
https://github.com/daisy/ace-gui/wiki/Localization

**Comment by danielweck** [comment]
Related Pull Request: 
https://github.com/daisy/ace/pull/246
