### ISSUE TITLE
error:   Unexpected error: Failed to launch chrome!

### ISSUE THREAD

**Issue by sinharoop** [daisy/ace#221]
Node Version: v8.10.0
NPM Version: 3.5.2
OS: UBUNTU 18.0

verbose: Ace 1.0.2, Node v8.10.0, Linux 4.15.0-39-generic
verbose: Options: cwd=/home/eb-01, outdir=/home/eb-01/Documents/2ProjectFolder/HC/HC003016, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing /home/eb-01/Documents/2ProjectFolder/HC/HC003016/TheGirlFromGalloway.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/tmp/tmp-9608GBVAuRouWaN0'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    - OPS/content.opf: 4 issues found
error:   Unexpected error: Failed to launch chrome!
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 18: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ?Udmv~�����������: not found
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 19: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: Syntax error: ")" unexpected
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: �
@8
  @,*@@@hh���,+r,+r0r0r0r: not found
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ELF: not found

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**debug:   Error: Failed to launch chrome!**

/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 18: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ?Udmv~�����������: not found
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 19: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: Syntax error: ")" unexpected
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: �
@8
  @,*@@@hh���,+r,+r0r0r0r: not found
/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: 1: /usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/.local-chromium/linux-609904/chrome-linux/chrome: ELF: not found

TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:342:14)
    at Interface.helper.addEventListener (/usr/local/lib/node_modules/@daisy/ace/node_modules/puppeteer/lib/Launcher.js:331:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.

**Comment by danielweck** [comment]
Is this still a problem with the latest version of Ace?
Version `1.1.1`:
https://www.npmjs.com/package/@daisy/ace
https://unpkg.com/browse/@daisy/ace@1.1.1/

**Comment by danielweck** [comment]
Note that there is a pending Pull Request that implements an alternative Electron-based "Axe runner" to the default Puppeteer-based one. This Electron implementation is used in the Ace App (sister `ace-gui` project), but it can also be called from the command line as an alternative to the default `ace-cli` tool. I am not recommending this for end-users, but just thought it was worth exploring, for users who have problems with Puppeteer's Chromium.
https://github.com/daisy/ace/pull/236

**Comment by danielweck** [comment]
See resolution in https://github.com/daisy/ace/issues/340
