### ISSUE TITLE
Use headless Chrome?

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#23]
Chrome can now be run headless. We can try some experiments to replace NightmareJS by e.g. [Chromeless](https://github.com/graphcool/chromeless) or a similar library.

**Comment by danielweck** [comment]
also see https://github.com/joelgriffith/navalia/issues/39

**Comment by rdeltour** [comment]
Nightmare is working on headless Chrome in the [v3 branch](https://github.com/segmentio/nightmare/tree/v3). 
We could also possibly directly use [puppeteer,](https://github.com/GoogleChrome/puppeteer) Google's Node API for headless Chrome.

**Comment by rdeltour** [comment]
Tentatively putting this in `vNext`, we should definitely start experimenting after v1.0.0 is out.
