### ISSUE TITLE
NodeJS support starts at version 6, why?

### ISSUE THREAD

**Issue by danielweck** [daisy/ace#232]
From the current `master` branch:
https://github.com/daisy/ace/blob/34c6e4704aae3793e9e854966428b5b54e246fad/.babelrc#L8

Does such an old runtime really need to be supported? Was there a feature request to back this decision? (sorry, I wasn't a contributor back then :)

https://nodejs.org/en/
LTS (Long Term Support) is currently `10.16`
"Current" is `12.4`

Electron version `5` (which AceGUI is based on) uses Node version `12`:
https://github.com/electron/electron/releases/tag/v5.0.3

I use a separate branch to build Ace GUI, where I upgrade the Babel transpiler setting:
https://github.com/daisy/ace/pull/229/files

**Comment by danielweck** [comment]
Note that attempting to build with the latest packages (as per allowed semver range) breaks the Node 6 build:

`error ansi-escapes@4.1.0: The engine "node" is incompatible with this module. Expected version ">=8".`
https://travis-ci.org/daisy/ace/builds/528544848 ( https://travis-ci.org/daisy/ace/jobs/528544851 )

See PR: https://github.com/daisy/ace/pull/231

**Comment by rdeltour** [comment]
Closing, as we decided to remove support for Node 6.
