### ISSUE TITLE
Rule epub-type-has-matching-role for Epigraphs

### ISSUE THREAD

**Issue by wolfmatthewj** [daisy/ace#234]
The following snippet brings up an epub-type-has-matching-role error from Ace: 

`section xmlns="http://www.w3.org/1999/xhtml" class="main-document-section" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="epigraph" role="doc-chapter"`

Up until we started using EPUBCheck 4.2.1 this week, I had been putting role="doc-epigraph" on these `section`s. But it looks like that role is supposed to go on `blockquote` only? Not sure if this is an Ace or an EPUBCheck error, to be honest.

**Comment by rdeltour** [comment]
> Not sure if this is an Ace or an EPUBCheck error, to be honest.

It's more a spec issue, in fact.

Currently, `doc-epigraph` is not allowed on `section` elements, as per the [ARIA in HTML](https://www.w3.org/TR/html-aria/#section) specification, so EPUBCheck is correct in reporting that.

At the same time, Ace will report a "best practice" issue when an `epub:type` is used without its matching ARIA role (when there is one).

That said, whether `doc-epigraph` should be allowed on `section` elements is still open for debate by the Digital Publishing Working Group, and this situation might change in the future.

In the meantime, there are several options to work around this issue:

- do not use the "epigraph" `epub:type`
- use  the "epigraph" `epub:type` on `blockquote` elements
-  use the "epigraph" `epub:type` on any semantically neutral element (like `div`), which would allow you to have a structure like the following:

```html
<section>
  <div epub:type="epigraph" role="doc-epigraph">
   …
  </div>
</section
```

**Comment by rdeltour** [comment]
I'm closing this issue as `wontfix`. We can reopen if/when the specs change. Feel free to keep commenting anyway!

**Comment by wolfmatthewj** [comment]
Thanks for the explanation, and the workarounds!

**Comment by laudrain** [comment]
Any news from the spec front ?

**Comment by rdeltour** [comment]
> Any news from the spec front ?

Not that I know… We need to work on this in the Publishing WG.

**Comment by laudrain** [comment]
@rdeltour you probably mean the EPUB3 CG?
The line epigraph in the role mapping table should allow for this role on HTML section tag.
@mattgarrish is it possible to update this mapping?

**Comment by rdeltour** [comment]
> @rdeltour you probably mean the EPUB3 CG?

No, I meant the Publishing WG, as anything related to DPUB ARIA is supposed to happen there no?
But well, it's the same people in that case so I doubt it makes any difference 😁

**Comment by pkra** [comment]
@laudrain @laudrain since this is ARIA-in-HTML territory, you could also file an issue at https://github.com/w3c/html-aria/. For comparison, I recently filed https://github.com/w3c/html-aria/issues/173 which is the same kind of issue (and received a positive response).

**Comment by mattgarrish** [comment]
There isn't any reason why it shouldn't be allowed on `section`. The ARIA mappings were done based on the examples in the spec, I believe, so we periodically encounter these kinds of issues where not all the uses are accounted for.

I can't make the changes, though. As @pkra has already said, you need to open an issue on that specification. It might be simplest just to comment on his issue that it also is used on `section`.

After that, you also need to get the validator updated. (Romain sometimes updates ace checking in advance, but we need the code base officially updated and that usually requires the mappings be corrected first.)

**Comment by pkra** [comment]
@mattgarrish a new issue is probably better since w3c/html-aria#173 is about role=doc-dedication on aside elements. I'll be happy to help pushing both items forward on the ARIA end.

**Comment by mattgarrish** [comment]
> is about role=doc-dedication on aside elements

D'oh, my brain has warmed up yet. For some reason I thought this was about dedication, too... :)

**Comment by laudrain** [comment]
This epigragh case is the **only one line** in the mapping where **an epub:type value is mapped to a role value with no element allowed on**.
It may be an oversight.

**Comment by pkra** [comment]
@laudrain that's not quite correct. Some elements have "any role", in particular blockquote (https://www.w3.org/TR/html-aria/#p-pre-blockquote) which is the example in DPUB ARIA (https://w3c.github.io/dpub-aria/#doc-epigraph).

**Comment by pkra** [comment]
I've filed https://github.com/w3c/html-aria/issues/177

**Comment by laudrain** [comment]
@pkra I am refering to the document https://idpf.github.io/epub-guides/epub-aria-authoring/ where I see only one line where an epub:type value is mapped to a role value (ni-on empty and different from "No Role") and has an empty cell in column "Elements Allowed On". It is the line for epigraph.

I support @mattgarrish comment:

> There isn't any reason why it shouldn't be allowed on section.

**Comment by laudrain** [comment]
And yes in https://w3c.github.io/dpub-aria/, doc-epigraph is said to-have:
> Superclass Role: | section
https://w3c.github.io/dpub-aria/#doc-epigraph

So it may be that this was not reported to the mapping in https://idpf.github.io/epub-guides/epub-aria-authoring/  which BTW is uesed by Ace a s a reference.

@mattgarrish @rdeltour could this mapping be fixed and Ace also ?

**Comment by pkra** [comment]
w3c/html-aria#177 has been fixed.

**Comment by laudrain** [comment]
@pkra great, thanks !
Now I think that [EPUB Type to ARIA Role Authoring Guide](https://idpf.github.io/epub-guides/epub-aria-authoring/) has to be changed, and after that Ace checks.

**Comment by rdeltour** [comment]
I'm reopening this issue, so that we can fix it in the next Ace version.

**Comment by danielweck** [comment]
Fixed in Axe and Ace:
https://github.com/daisy/axe-core/pull/4
https://github.com/daisy/ace/pull/314
