### ISSUE TITLE
`accessModeSufficient` value check is broken, as the metadata accepts a list of values

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#238]
Reported by @garconvacher:
 
The following markup:
```xml
<meta property="schema:accessModeSufficient">textual,visual</meta>
```

will be reported as:
```
metadata-accessmodesufficient-invalid (Moderate) : 'schema:accessModeSufficient' metadata must be set to one of the expected values
```

**Comment by laudrain** [comment]
@rdeltour knowledge base propose also with a space separator:
<meta property="accessModeSufficient" content="textual visual"/>
(http://kb.daisy.org/publishing/docs/metadata/schema-org.html)
Ace 1.1 reports is as an error also !

**Comment by mattgarrish** [comment]
EPUB can't represent [the expected ItemList defined in schema.org](https://schema.org/accessModeSufficient), so this is one of the cases where we had to come up with a workaround.

Both tend to be acceptable, and we should probably be permissive from a validation standpoint. The KB actually mixes both, as the full example uses commas but the individual definition does not. (I have a memory that we decided to use commas somewhere near the end of the a11y spec revision just to make clear that there was a list as the value, but it's not an enforced requirement in any document.)

**Comment by mattgarrish** [comment]
Skimming the techniques document, we did put this statement in:

> The order in which the access modes are listed is not important. The only requirement is that they be separated by commas.
http://www.idpf.org/epub/a11y/techniques/#meta-002

It's not a normative document, though, so "requirement" here is just a descriptive statement of what we were expecting.

**Comment by laudrain** [comment]
Sorry but I don't see the resolution of this issue !

Should we remove:
`<meta property="schema:accessModeSufficient">textual,visual</meta>`
?

**Comment by rdeltour** [comment]
@laudrain have you updated to v1.1.1? (released on Monday July 8)

**Comment by laudrain** [comment]
Ah yes, thanks. I'll do it immediately

**Comment by laudrain** [comment]
Perfect, no more issue in 1.1.1!

**Comment by laudrain** [comment]
@rdeltour ace --version still gives 1.1.0

**Comment by rdeltour** [comment]
> @rdeltour ace --version still gives 1.1.0

yes, I realized that yesterday, with feedback from @clapierre.
