### ISSUE TITLE
role 'directory' used on `ol` or `ul` causes Axe `listitem` rule to be reported

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#239]
When an `ol` element as the role `directory` (as for instance in the [DPUB ARIA `doc-toc` example](https://www.w3.org/TR/dpub-aria-1.0/#doc-toc)), Axe will report a `listitem` error:

```
listitem (Serious) : List item does not have a <ul>, <ol> or role="list" parent element
```

I don't know if it's a bug or intentional (lack of a11y support). To be investigated…

Thanks @garconvacher for the report!

**Comment by rdeltour** [comment]
Reported to Axe as dequelabs/axe-core#1677

**Comment by danielweck** [comment]
https://github.com/dequelabs/axe-core/issues/1677#issuecomment-718022025

> Looking at this again. At this point both directory and doc-biblioentry are proposed to be deprecated, exactly for the reason that its inheritance creates confusion. Neither of these use cases is valid according to ARIA 1.1, so we're going to leave these as failures for axe-core.
