### ISSUE TITLE
'ace -version' still output 'v1.1.0' on v1.1.1

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#245]
I forgot to update the new `ace-meta` module 🤦‍♂️

**Comment by danielweck** [comment]
Oopsy :(
https://github.com/daisy/ace/blob/be5d8a4154a2a38a07b28475f9e0538d91a0bab3/packages/ace-meta/package.json#L3

**Comment by rdeltour** [comment]
I silently published `ace-meta` v1.1.1 to the npm repo, so that's fixed for the future installs.

We could add a warning to update that at build time (to be done when we try to streamline the build process).

**Comment by rdeltour** [comment]
@clapierre @laudrain you can re-run the Ace install command and it will fetch the correct version number (I didn't want to publish v1.1.2 just for that). Sorry for the mishap and thanks for the report!

**Comment by laudrain** [comment]
@rdeltour thanks !

**Comment by clapierre** [comment]
18-019:~ charlesl$ ace -v
1.1.1

:) Happy happy!
