### ISSUE TITLE
Non-localized string on Ace Report

### ISSUE THREAD

**Issue by thiagoeec** [daisy/ace#249]
There is a string missing localization on the Ace Report:

https://github.com/daisy/ace/blob/bf8b37442d5557d056d131057a8213ba24334c6e/packages/ace-report/src/report-template.handlebars#L514

"No matching violations found"

**Comment by danielweck** [comment]
Good catch!!

**Comment by danielweck** [comment]
Fixed in this PR: https://github.com/daisy/ace/pull/250

In the meantime, could you please add `noMatchingViolations` to your PR?

Many thanks!

**Comment by thiagoeec** [comment]
> Fixed in this PR: #250

Thanks. You were too fast. Just find another miss: when you use filters on the report, severity labels goes back to english.
I think it has to do with this:

https://github.com/daisy/ace/blob/bf8b37442d5557d056d131057a8213ba24334c6e/packages/ace-report/src/report-template.handlebars#L582-L598


> In the meantime, could you please add `noMatchingViolations` to your PR?

Sure!

**Comment by danielweck** [comment]
@thiagoeec I created a new issue to tackle the filters:
https://github.com/daisy/ace/issues/251
