### ISSUE TITLE
Requesting the ability to run on expanded EPUB folders

### ISSUE THREAD

**Issue by CircularKen** [daisy/ace#255]
I would like ACE CLI to be modified so I can interrogate an open folder rather than a ZIPped EPUB.

Currently, I’m having to continually compress to check and uncompress to then fix and then compress again to check once more!

For example the neat pagina EPUB-checker validation GUI that I use has this simple and useful feature and it speeds up EPUB development considerably.

I am using ACE 1.0.2

Thanks everyone, keep up the good work!

**Comment by danielweck** [comment]
Related issue: https://github.com/daisy/ace-gui/issues/67

**Comment by danielweck** [comment]
I've just tested Ace (CLI) from the `master` branch as well as from the branch used by Ace App (the desktop GUI). I am able to check packed EPUBs as well as unzipped ones.

**Comment by danielweck** [comment]
I have also tested the latest official package:

`npx @daisy/ace-cli  -o ~/Desktop/out/ -f -V /Users/danielweck/Desktop/accessible_epub_3.epub`

`npx @daisy/ace-cli  -o ~/Desktop/out/ -f -V /Users/danielweck/Desktop/accessible_epub_3/`

...all good. Could you please double-check the bug at your end?

**Comment by danielweck** [comment]
So, I haven't tried `1.0.2`, but this works fine in the latest version `1.1.1`.

`npx @daisy/ace-cli -v`
=>
`1.1.1`

https://unpkg.com/browse/@daisy/ace-cli@1.1.1/package.json

**Comment by danielweck** [comment]
I confirm that version `1.0.2` crashes with a folder:

`npx @daisy/ace-cli@1.0.2 -o ~/Desktop/out/ -f -V ~/Desktop/accessible_epub_3/`
=>
```
npx: installed 119 in 10.824s
verbose: Ace 1.1.1, Node v10.16.0, Darwin 18.7.0
verbose: Options: cwd=~/Desktop, outdir=~/Desktop/out/, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing ~/Desktop/tmp/
verbose: EPUB is already unpacked
info:    Parsing EPUB
verbose: at location '~/Desktop/tmp'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    - EPUB/package.opf: 4 issues found
error:   Unexpected error: Cannot read property 'launch' of undefined
debug:   TypeError: Cannot read property 'launch' of undefined
    at Object.module.exports.check (~/.npm/_npx/4661/lib/node_modules/@daisy/ace-cli/node_modules/@daisy/ace-core/lib/checker/checker-chromium.js:115:19)
    at epubChecker.check.then (~/.npm/_npx/4661/lib/node_modules/@daisy/ace-cli/node_modules/@daisy/ace-core/lib/checker/checker.js:41:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)
    at findNodeScript.then.existing (/usr/local/lib/node_modules/npm/node_modules/libnpx/index.js:268:14)
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.
```

**Comment by danielweck** [comment]
Uh, wait, I am getting an error with a packed EPUB as well, maybe this is a NPM / `npx` cache-related error:

`npx @daisy/ace-cli@1.0.2 -o ~/Desktop/out/ -f -V ~/Desktop/accessible_epub_3.epub`

```
npx: installed 119 in 4.342s
verbose: Ace 1.1.1, Node v10.16.0, Darwin 18.7.0
verbose: Options: cwd=~/Desktop, outdir=~/Desktop/out/, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing ~/Desktop/accessible_epub_3.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/var/folders/f4/bs_1cm7565jdq6tzs0n01h_40000gn/T/tmp-4702pfDYvsGmJ7oC'
info:    Analyzing accessibility metadata
info:    Checking package...
info:    - EPUB/package.opf: 4 issues found
error:   Unexpected error: Cannot read property 'launch' of undefined
debug:   TypeError: Cannot read property 'launch' of undefined
    at Object.module.exports.check (~/.npm/_npx/4702/lib/node_modules/@daisy/ace-cli/node_modules/@daisy/ace-core/lib/checker/checker-chromium.js:115:19)
    at epubChecker.check.then (~/.npm/_npx/4702/lib/node_modules/@daisy/ace-cli/node_modules/@daisy/ace-core/lib/checker/checker.js:41:65)
info:    Closing logs.
Re-run Ace using the --verbose option to enable full debug logging.
```

**Comment by danielweck** [comment]
At any rate, the bug does not exist in the latest published version of the Ace core packages, so let's close this issue. Please feel free to re-open if you feel it is necessary :) Thanks for your feedback!
