### ISSUE TITLE
Axe Runner Puppeteer vs. Electron: no images reported with a particular EPUB (InDesign export)

### ISSUE THREAD

**Issue by danielweck** [daisy/ace#263]
Puppeteer Axe Runner:
`node packages/ace-cli/bin/ace.js -V -f -o ~/Desktop/out-puppeteer/ ~/Desktop/xxx.epub `

Electron Axe Runner:
`node node_modules/electron/cli.js packages/ace-axe-runner-electron/lib/cli.js  -V -f -o ~/Desktop/out-electron/ ~/Desktop/xxx.epub`

Or:
`./compareAxeRunners.sh ~/Desktop/xxx.epub`

=> "timeouts" in the log.

Investigating...

**Comment by danielweck** [comment]
Fixed. The safety / fallback timeout implemented in the Electron Axe Runner was too conservative / did not allow enough time for large documents to be analyzed by Axe.

**Comment by danielweck** [comment]
Very similar performance between the Puppeteer and Electron Axe Runners:

`./compareAxeRunners.sh ~/Desktop/xxx.epub`

=>

```
PuppeteerAxeRunner ...
>>> ACE PERF: 13 seconds + 109975955 nanoseconds
ElectronAxeRunner ...
>>> ACE PERF: 13 seconds + 629076505 nanoseconds
```

The EPUB is 35MB (which isn't an interesting metric here), there are several XHTML documents over 300KB, with lots of images loading inside.

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace/commit/64e34b9d0eff5795039d35b1128780b2eedb640b

**Comment by danielweck** [comment]
Ah, I came across random / hard-to-reproduce-consistently timeouts, and I discovered why. I implemented a proper / more reliable fix now:
https://github.com/daisy/ace/commit/368f8c3d98f87de9ac5b58e876bc742c2c6b62c7

**Comment by clapierre** [comment]
@danielweck I know this is closed but was this fixed in a way which if this happens in the future it just doesn't fail silently but will bring up an error message saying that something went wrong and you shouldn't trust the results in the HTML report?

**Comment by danielweck** [comment]
Hello @clapierre error reporting in Ace CLI is via the log file, as well as displayed in the console when verbosity is enabled. Things are a little more complicated in the Ace App / GUI (which is where the timeout issue manifested itself), and this is a more general problem that we will tackle.
