### ISSUE TITLE
Create a wiki page to document the build process and developer scripts

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#268]
- quickly document the purpose and usage of all the npm scripts in the main `package.json` script
- document the extra maintenance tools that can be used optionally (e.g. `ncu`, etc)

**Comment by danielweck** [comment]
Note that documentation about the localization tooling / scripts has its own dedicated wiki pages:
https://github.com/daisy/ace/wiki/Localization
https://github.com/daisy/ace-gui/wiki/Localization

**Comment by danielweck** [comment]
Done:
https://github.com/daisy/ace/wiki/Developer-Workflow
https://github.com/daisy/ace-gui/wiki/Developer-Workflow
(both linked from their respective main READMEs)

There's probably (surely) room for improvement, but I suggest we close this issue now.
