### ISSUE TITLE
Remove the HTML outline

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#269]
The outline view currently displays 3 outlines side by side:

- the ToC from the Nav Doc 
- the headings outline
- the outline from the HTML outline algorithm

This last outline is basically useless for accessibility (it's not implemented by any browser or AT), and was mostly added there for people who found it useful as a way to check their markup structure. As it's probably more confusing than helpful for most users, I suggest we simply remove it for now, and maybe hide it as an opt-in feature later.

**Comment by danielweck** [comment]
Should this issue be moved to the `ace-gui` repository?

**Comment by rdeltour** [comment]
> Should this issue be moved to the `ace-gui` repository?

No, the data gathering is part of `ace-core`, and the rendering is part of `ace-report`.

That said, once the outline is removed, we'll probably need to also adapt the GUI code indeed.

**Comment by danielweck** [comment]
I see, I initially thought this was only an issue in the GUI, but I do agree it is problematic in the HTML report too. Thanks for clarifying!

**Comment by danielweck** [comment]
Related issue: https://github.com/daisy/ace/issues/349
