### ISSUE TITLE
unique aria-label / title for landmarks (Invalid Link to KB)

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#273]
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [10.16.0] the version of Node used to run Ace (as returned by the `node -v` command).
- [Mac 10.14] your operating system and version.

Invalid link to KB

The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable
Learn more about: (no specific entry)

**Comment by danielweck** [comment]
Evidently, there is no KnowledgeBase entry for this type of reported issue.
Here are the currently-supported entries (do you see a good fit for "The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable"?):
https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report-axe/src/index.js#L19-L75

**Comment by danielweck** [comment]
Maybe `docs/script/aria.html` https://kb.daisy.org/publishing/docs/script/aria.html ?

**Comment by danielweck** [comment]
"The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable" comes from `landmark-is-unique`:

https://github.com/dequelabs/axe-core/blob/master/lib/checks/landmarks/landmark-is-unique.json

**Comment by danielweck** [comment]
I created a Pull Request (to be reviewed):
https://github.com/daisy/ace/pull/279

**Comment by danielweck** [comment]
Charles, could you please share the EPUB so we can reproduce the exact Axe check/rule at our end? Thank you!

**Comment by diagram-codesprint** [comment]
I will check with the publisher to ensure I can pass it on to you, I will send it directly to you Daniel if they approve as I wouldn't be able to put it in here.

**Comment by clapierre** [comment]
@danielweck I will check with the publisher and send you the EPUB directly once they approve.
Thanks

**Comment by laudrain** [comment]
@danielweck yes it comes from the rules of uniqueness of landmarks, but as I stated in [issue 271](https://github.com/daisy/ace/issues/271), I cannot find any exhaustive list of landmark roles !

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace/pull/299
