### ISSUE TITLE
Update axe-core to release 3.3.2

### ISSUE THREAD

**Issue by nvdaes** [daisy/ace#276]
This includes changes, for instance, spanish localization:
https://github.com/dequelabs/axe-core/releases/tag/v3.3.2

**Comment by danielweck** [comment]
I forgot to say, the latest version of Axe is used in this Pull Request:
https://github.com/daisy/ace/pull/236
... which will soon be published as the next "beta" version of Ace.
This PR is already used by the Ace App.

**Comment by nvdaes** [comment]
danielweck commented 7 hours ago 

> I forgot to say, the latest version of Axe is used in this Pull Request:
#236
... which will soon be published as the next "beta" version of Ace.
This PR is already used by the Ace App.

OK. When ACE beta and a new RC or stable of the app are released, I will inform on spanish mailing lists and on Twitter so people can test the localized version.
Thanks for all your work and info. 👍

**Comment by danielweck** [comment]
Ace App has "nightly" builds / continuous integration and deployment (see the release section of the ace-gui GitHub repository)

The latest pre-release version of Ace command line is currently published as 1.2.0-beta.2 under the "next" tag (npm install @daisy/ace@next)

You might need to uninstall version 1.1.1 (or any other globally-installed Ace) so that the executable command line script does not have duplicates.

**Comment by nvdaes** [comment]
Thanks, I see that messages translated in ACE and ace-gui are generally shown, but for now localized axe rules seem not to be included. I will be testing future versions of Ace command line and app.

**Comment by danielweck** [comment]
Yes, I reported a bug in Axe core regarding missing locales.
https://github.com/dequelabs/axe-core/issues/1811

**Comment by nvdaes** [comment]
Yes, I know this and hope it can be fixed.
Thanks for your attention.

**Comment by nvdaes** [comment]
@danielweck , you can update axe-core using release 3.4.0. This includes spanish localization.
Thanks.

**Comment by danielweck** [comment]
Axe `3.4.0` is integrated in the Ace `1.2.0-beta.3` (`npm install @daisy/ace@next`):
https://www.npmjs.com/package/@daisy/ace/v/1.2.0-beta.3

Source code:
https://github.com/daisy/ace/pull/236
https://github.com/daisy/ace/tree/feature/axe-runner-electron

**Comment by nvdaes** [comment]
OK, I will share this in spanish community. Thanks for your attention
and all your work. This ap is wonderful.

2019-10-24 12:46 GMT+02:00, Daniel Weck <notifications@github.com>:
