### ISSUE TITLE
HTML report should be offline, should include all Javascript + CSS dependencies in folder

### ISSUE THREAD

**Issue by danielweck** [daisy/ace#278]
The HTML report is currently not purely an offline document, it needs to connect to the web in order to apply Javascript and CSS (in order to enable the rich report rendering / interaction features). As a result, loading the `report.html` from `file://` instead of a web server / HTTP URL is cause for various CORS warnings / errors.

https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report/src/report-template.handlebars#L4-L5

https://github.com/daisy/ace/blob/5d4cc866af8141180980522748c0aa82830afb7a/packages/ace-report/src/report-template.handlebars#L459-L463

Related / originating issue:
https://github.com/daisy/ace/issues/277

**Comment by hatton** [comment]
Most people wouldn't notice, but [Bloom](https://bloomlibrary.org/page/create/page/about) relies on Ace to check the accessibility of EPUBs it creates. This check is the only feature that requires users (often in poor countries) to be online.

**Comment by danielweck** [comment]
Hello, thank you for your feedback. This was recently fixed in the latest Ace release, actually.
