### ISSUE TITLE
role="doc-cover" results in failure

### ISSUE THREAD

**Issue by VeryGoodErotica** [daisy/ace#282]
Please provide the following details if possible or relevant:

ace 1.1.1
node v10.16.3 - installed from binary tarball
CentOS Linux release 7.6.1810 (Core)

Here is the relevant XHTML:

    <?xml version="1.0" encoding="UTF-8"?>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"
      xmlns:epub="http://www.idpf.org/2007/ops">
    <head>
      <meta charset="utf-8" />
      <title>Cover Page</title>
      
    </head>
    <body epub:type="frontmatter">
    <div epub:type="cover">
    <svg xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      version="1.1" width="100%" height="100%" role="doc-cover"
      aria-label="Book Cover Image of woman holding a beer"
      aria-describedby="thesvgtitle thesvgdesc"
      viewBox="0 0 800 1120" preserveAspectRatio="xMidYMid">
      <title id="thesvgtitle">Cover Page Art</title>
      <desc id="thesvgdesc">
        [snip]
      </desc>
      
    </svg>
    </div>
    </body>
    </html>

When `role="img"` then ace does not have any complaints.
But when `role="doc-cover"` I then get the WCAG 2.0 A error.

The test it says it fails is `aria-dpub-role-fallback`

More detailed is `Element’s implicit ARIA role is not a good fallback for the (unsupported) role`

It is my understanding that `doc-cover` is suppose to be used for cover art image node, which is what svg node is, so an error shouldn't be generated.

**Comment by danielweck** [comment]
Thank you for reporting, @VeryGoodErotica

I think this issue was addressed here:
https://github.com/daisy/ace/issues/233#issuecomment-508760097

I am closing this issue as "duplicate", but please feel free to re-open if you feel this is not a satisfactory answer.

**Comment by VeryGoodErotica** [comment]
Okay, it looks like identical issue and if I read it right, the issue is that AT may not understand it is an image if I use role="doc-cover" instead of role="img" so the best thing to do w/ respect to having something that works for the users is just use role="img".
