### ISSUE TITLE
Metadata needs unique separators for lists

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#283]
AccessModeSufficient contains lists of values which can be the same value repeated and having everything separated by a comma is confusing:

IE: 
schema:accessModeSufficient | textual,visual,audio,textual,audio,visual

I would suggest having a different separator such as a ; between each list item or putting <> around each list item

schema:accessModeSufficient | textual,visual,audio; textual; audio,visual
or
schema:accessModeSufficient | <textual,visual,audio>,<textual>,<audio,visual>
but could have been a number of other possible combinations as well.

NOTE: that is a made up example but shows how this is confusing without separation of the lists

**Comment by rdeltour** [comment]
> AccessModeSufficient contains lists of values which can be the same value repeated and having everything separated by a comma is confusing

Do you mean this happens in the Ace report?

Yes multiple `acessModeSufficient` combinations need to be clearly identified. Having one per line, or grouped between parenthesis are other options.

**Comment by clapierre** [comment]
Yes correct in the Ace Report under Metadata.  And Yes that sounds good what you are thinking either way.  Thanks

**Comment by danielweck** [comment]
Code references:

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report-template.handlebars#L333-L365

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/analyze-a11y-metadata.js#L31-L65

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report.js#L52

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report-builders.js#L122-L126

**Comment by danielweck** [comment]
Code references:

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report-template.handlebars#L333-L365

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/analyze-a11y-metadata.js#L31-L65

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report.js#L52

https://github.com/daisy/ace/blob/d5e7be6a084c766da1ec23f40622fb6dd403f323/packages/ace-report/src/report-builders.js#L122-L126

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace/commit/46db32016e536c9ebf5f7ed4b4c98cb7f74fd076
(will be published in `@daisy/ace` NPM package version `1.2.0-beta.8`,  under the "next" tag ( see all available versions at https://www.npmjs.com/package/@daisy/ace ).
