### ISSUE TITLE
ace plugin failed

### ISSUE THREAD

**Issue by failedpi** [daisy/ace#285]
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [8.9.4] the version of Node used to run Ace (as returned by the `node -v` command).
- [sigil] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- []
![acePlugInError](https://user-images.githubusercontent.com/56065080/66025332-28ab8b80-e531-11e9-888c-7593e34bae2f.png)

 if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

**Comment by danielweck** [comment]
This looks like an integration problem, not one that can be solved directly in the Ace project. Could you please contact the relevant development team / programmer for either the Sigil or Calibre Ace plugins:

Sigil plugin:
https://www.mobileread.com/forums/showthread.php?t=247431
=>
https://www.mobileread.com/forums/showthread.php?t=294678

Calibre plugin:
https://plugins.calibre-ebook.com/
=>
https://www.mobileread.com/forums/showthread.php?t=313848

**Comment by failedpi** [comment]
Thks for the answer. It was 'path' problem...
