### ISSUE TITLE
Localization: french word "violation" should be replaced by "erreurs"

### ISSUE THREAD

**Issue by editadapt** [daisy/ace#288]
The french word "violation" is a bit strong, it refers to legal or religious infractions. It should be replaced by a more neutral term like "erreurs".

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/ace/commit/e6b5fa743d5315d493b11db6cfa5825979e0385b
and via https://github.com/daisy/ace-gui/commit/de4d9d2affad0b38662cf8cddc4b9423d35e407b
