### ISSUE TITLE
How to convey violations’ severities?

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#29]
Currently violations have an "impact" information, which comes from aXe and can be either "minor", "moderate", "serious", or "critical".

Should we keep this info as-is? Its meaning would at least need to be described (in user guide, but possibly also in a short help text in the report).

**Comment by mattgarrish** [comment]
This is interesting, as this is also a question I had about failing publications. There are serious failures and less serious annoyances. Do we want to categorize failures to help comprehension of the potential usability, or could it get to be too subjective an exercise?

Probably something to figure out for a post 1.0 release.

**Comment by josteinaj** [comment]
Would it be possible to expose the most serious impact value in a machine-readable way? I'm adding ACE into our workflow and think it might be nice to signal whether things look good or bad in the e-mail I send automatically to producers before they open the report. i.e. red/yellow/green color.

If the current "impact" values are unsuited for this, maybe some other overall "report status" could be provided?

**Comment by rdeltour** [comment]
>  Would it be possible to expose the most serious impact value in a machine-readable way?
Yes, if we decide to keep this impact info, it makes sense to compute the most serious impact at a higher level.

> maybe some other overall "report status" could be provided?
How would that be different from the global `earl:outcome` property we already have, can you please clarify?

**Comment by josteinaj** [comment]
Ah, I didn't know about the `earl:outcome`. That looks perfect, I'll use that one. Thanks!

**Comment by laudrain** [comment]
Starting with version 0.8 beta 4, you should also be able to use the command line return code (see issue #113)

**Comment by rdeltour** [comment]
Closing this issue. The testing raised no questions on this `impact` information.
