### ISSUE TITLE
OPF manifest item href with percent-encoded URL results in filepath failure 

### ISSUE THREAD

**Issue by gregoriopellegrino** [daisy/ace#290]
Please provide the following details if possible or relevant:

- Ace GUI 1.0.0-rc.1
- macOS 10.14.5

I downloaded an EPUB 2, launched the DAISY app, selected it for checking, but I get no results.

In the log I see:
```
Running Ace on /Users/uu/Downloads/Test ebook.epub
[object Object]
```

I can send you the file privately.

**Comment by danielweck** [comment]
I am able to reproduce this bug in the latest "beta" Ace CLI ( https://www.npmjs.com/package/@daisy/ace/v/1.2.0-beta.4 ) from this PR / branch https://github.com/daisy/ace/pull/236
This is definitely an issue related to URL escaping / percent-encoding. I am looking into it.

**Comment by danielweck** [comment]
The latest "beta" version (`1.2.0-beta.4`) of Ace includes a fix for this issue (i.e. proper handling of URL percent-encoding and HTML URL escaping on all ZIP resources, including support for non-ASCII chars in file names).

@gregoriopellegrino I tested the fix with your publication `Zenaro esercitazione ebook.epub`
You may try this yourself by installing Ace "beta" from the `next` NPM release channel:
`npm install --global @daisy/ace@next` (alternatively, you may remove `--global` to install the Ace packages locally, inside a folder-contained NPM project)

Notes to developers:
https://www.npmjs.com/package/@daisy/ace/v/1.2.0-beta.4
... is built from the codebase in this PR / branch https://github.com/daisy/ace/pull/236

Git commit:
https://github.com/daisy/ace/commit/009142f560cff59bb860c54c03d3a559807d4113

New unit test:
https://github.com/daisy/ace/commit/0d143bb7d8d6d7f77c2eefb3c3f2c08eb5e89b79

**Comment by gregoriopellegrino** [comment]
It works great, thanks!
