### ISSUE TITLE
role attribute mandatory on each img tag ?

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#296]
Please provide the following details if possible or relevant:

- [1.1.1] the version of Ace impacted by the issue (as returned by the `ace -v` command).
- [] the version of Node used to run Ace (as returned by the `node -v` command).
- [] your operating system and version.
- [] if the issue is a bug when running Ace: the error message as produced in the log file (you can enable debug logging with the `--verbose` option).
- [] if the issue is about the HTML report: the browser(s) and version(s) you used.
- [] if possible, let us know if you can share a sample input file to help us reproduce the issue.

With Ace 1.1.1, as role="doc-cover" has been deconnected from epub:type="cover", cover images without any role attribute are ok !

Has it been discussed that ARIA role attribute should be mandatory on each img HTML tag ?
This would help Ace detect missing role attributes.

Or if we could write custom rules, we could manage that "doc-cover" specific case (see #84).

**Comment by rdeltour** [comment]
Is it the same issue as #297?

> Has it been discussed that ARIA role attribute should be mandatory on each img HTML tag ?

I'm not sure I understand; could you elaborate?

**Comment by laudrain** [comment]
Issue #297 is a single rule on one image.
In this issue, I'm wondering if there are rules for all images regarding role attribute.
We know about alt text for WCAG, but if there was some rule for role attribute, it would be possible to specify strategies to build extended checking.

**Comment by rdeltour** [comment]
> We know about alt text for WCAG, but if there was some rule for role attribute, it would be possible to specify strategies to build extended checking.

The rules are known and well defined in HTML, and ARIA in HTML, as with any other HTML elements. Essentially, there is absolutely no need to have a `role` attribute on `img` elements, as it has an implicit `img` role when an `alt` text is present, and no semantics when the `alt` attribute is empty. This is widely supported on browsers and ATs, so no explicit role is required.

**Comment by rdeltour** [comment]
I'm closing this issue as `invalid` since there is nothing to check specifically here. Feel free to keep on commenting, or reopen if you want to suggest a specific new check.
