### ISSUE TITLE
AccessibilityFeature Invalid: location field misleading

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#304]
Here is the output from Ace.

Moderate | EPUB | metadata-accessibilityfeature-invalidAce | "7TH EDITION"OPS\content.opf | 'schema:accessibilityFeature' metadata must be set to one of the expected valuesLearn more about: Schema.org Accessibility Metadata
-- | -- | -- | -- | --

The actual accessibility feature was "mathML" instead of "MathML"
(case sensitivity is another issue to tackle on another day but it looked like to me that "7TH EDITION" was one of the accessibility Features they tried to add, but that was just the first 
    `<dc:title id="t2">7TH EDITION</dc:title>`
 
Ace encountered.

Not sure why 
   ` <meta property="schema:accessibilityFeature">mathML</meta>`

which caused the error would not have been what is reported.

**Comment by danielweck** [comment]
Indeed the information layout is confusing in this case.
In this table row, the column headings are: `impact`, `ruleset`, `rule`, `location`, `details`.
The string "7TH EDITION - OPS\content.opf" is in the `location` column, so this seems like its correct logical placement.
The last `details` column should provide the value found for `schema:accessibilityFeature`, so that the user knows what to look for.
I am also wondering about if/how this error report is echo'ed in the "metadata" section too, or if this is just reported in the "violations" tab.
What do you think?

**Comment by clapierre** [comment]
I like that idea of adding it also to the metadata tab as invalid metadata values.

**Comment by Shankar14** [comment]
The below validation issue clear (clapierre idea --- Thanks)
metadata-accessibility feature-invalid

**Comment by danielweck** [comment]
The latest build of Ace App (GUI Graphical User Interface) implements a UX improvement in the metadata tab: when there are metadata-related violations, there is now a link below the report table which takes the user into the violations tab, and which automatically filters the table rows to display only the metadata-related issues. Additionally, the violation description now includes information about erroneous values.

To try this feature, you may download the Linux, Windows or MacOS pre-release installer from this link https://github.com/daisy/ace-gui/releases (labelled "continuous test build")

**Comment by danielweck** [comment]
As for case sensitivity, `MathML` is valid, versus `mathML` which is not. This is correctly reported by the latest version of Ace.

**Comment by danielweck** [comment]
PS: by "latest version of Ace", I meant version `1.2.0-beta.7` of Ace "core" (i.e. command line tool, etc.), which is published as the regular `@daisy/ace` NPM package under the "next" tag ( see all available versions at https://www.npmjs.com/package/@daisy/ace ). This can be installed from the terminal with: npm install -g @daisy/ace@next.
Alternatively, the aforementioned build of Ace App (the GUI) includes the latest "beta" version of Ace CLI (see https://github.com/daisy/ace-gui/releases ).
