### ISSUE TITLE
role=heading missing from heading outline

### ISSUE THREAD

**Issue by pkra** [daisy/ace#308]
I'm using Ace v1.1.1 on node v12.10 (ubuntu 19.10).

Elements with role=heading (and, say, aria-level=1) do not seem to be included in the heading outline. 

E.g.,

```html
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" lang="en" xml:lang="en">
<head>
<title>Ace role heading test</title>
</head>
<body>
<div role="heading" aria-level="1">An H1!</div>
<p>Hello</p>
</body>
</html>
```

leads to "Untitled BODY" in the outlines.

**Comment by rdeltour** [comment]
> Elements with role=heading (and, say, aria-level=1) do not seem to be included in the heading outline.

Good catch, thanks for the report!

**Comment by pkra** [comment]
Thanks @rdeltour. Looks like 

https://github.com/daisy/ace/blob/896d1daa02a274b17add78c161337fe1e8199d6e/packages/ace-core/src/scripts/ace-extraction.js#L130

is to simple. I'm happy to try making a pull request.

**Comment by rdeltour** [comment]
Yes, I had a quick look at the code and came to the same conclusion. PR welcome of course!

**Comment by laudrain** [comment]
@pkra I understand the technical issue.
But i'm wondering why not use a <h1> tag in the first place instead of a <div>?

**Comment by pkra** [comment]
@laudrain this was just a minimal example to exhibit the bug minimal side effects. 

Of course, the [First Rule of ARIA](https://www.w3.org/TR/using-aria/#rule1) applies but sometimes authors cannot use the native HTML element and sometimes there is no native element (e.g., there is no h7 and above).

**Comment by laudrain** [comment]
@pkra understood.
