### ISSUE TITLE
doc-biblioentry role giving ACE error I do not understand.

### ISSUE THREAD

**Issue by VeryGoodErotica** [daisy/ace#311]
Please provide the following details if possible or relevant:

- [] version of Ace: 1.1.1
- [] the version of Node: v10.16.3
- [] OS: CentOS 7.7.1908 (GNU/Linux)

The HTML snippet, modeled after http://kb.daisy.org/publishing/docs/html/dpub-aria/doc-biblioentry.html

    <div role="list">
      <div id="allen-1895" role="listitem">
        <p epub:type="biblioentry" role="doc-biblioentry">
          <span class="author">Allen, J. A. <time>1895</time></span>.
          <span class="title">On a collection of mammals from Arizona and New Mexico, made by Mr. W. W. Price, with field notes by the collector</span>.
          <span class="journal">Bulletin of the American Museum of Natural History</span>,
          <span class="details">volume 7, <abbr>pp.</abbr> 193&#8211;258, 17 figures</span>.
        </p>
      </div>
      <div id="bailey-1905" role="listitem">
        <p epub:type="biblioentry" role="doc-biblioentry">
          <span class="author">Bailey V. <time>1905</time></span>.
          <span class="title">Biological survey of Texas</span>.
          <span class="journal">North American Fauna</span>,
          <span class="details"><abbr>no.</abbr> 25, <abbr>pp.</abbr> 1&#8211;222, 24 figures, 16 plates</span>.
        </p>
      </div>
    </div>

The Ace error:

Element’s implicit ARIA role is not a good fallback for the (unsupported) role

It does not surprise me that I am doing something wrong, before today I just used a definition list for bibliographies and just called it a epub:type="appendix" but that's clearly wrong, so I am trying to do it the correct way but I do not understand this ace error.

**Comment by rdeltour** [comment]
> Element’s implicit ARIA role is not a good fallback for the (unsupported) role

This issue is raised for practical reasons, because this markup isn't deemed sufficiently supported by some popular assistive technologies and browsers.

The `doc-biblioentry` is supposed to semantically represent an item in a bibliography list. So Ace warns when it isn't used on a list item element (which is a reaonsable fallback semantic if the DPUB ARIA role isn't recognized).

I'm closing the issue since it isn't specifically an issue with Ace, but please do feel free to keep on commenting here 😊

**Comment by VeryGoodErotica** [comment]
Okay I'll play around with it a bit and see if I can get css to do what I want with an unordered list.

BTW just to be clear, I am very appreciative of errors that exist because popular assistive technologies don't have the sufficient support. Such errors are the only way I can know right now that it won't work as I intend for such users, as I do not have access to the technologies to try them myself.

**Comment by VeryGoodErotica** [comment]
ul.bib {
      list-style-type: none;
      padding-left: 0;
    }

All I needed. The linked daisy.org page with an example however produces the same error as their examples puts `role="biblioentry"` in the `p` element that is child of `li` element. That gives a ePubCheck error, `role=doc-biblioentry` does not give an ePubCheck error but results in the same Ace error if it is on the `p` element as that page shows.

I guess that page needs to be updated?

http://kb.daisy.org/publishing/docs/html/dpub-aria/doc-biblioentry.html is the one I am referring to, specifically Example 1.

It's working fine for me now, but I'm using an ul and have the `role="doc-biblioentry"` on the `li` instead of on the `p`.
