### ISSUE TITLE
Incorrect validation result of schema:accessModeSufficient with more than two access modes

### ISSUE THREAD

**Issue by duenckel** [daisy/ace#313]
According to the [documentation](https://schema.org/ItemList) there is no limit to the amount of values for the 'schema:accessModeSufficient' metadata:

> A list of single or combined accessModes (...)

But when the 'schema:accessModeSufficient' metadata is set to more than two combined access modes, the Ace "metadata-accessmodesufficient-invalid" assertion is fired.

- [x] Ace version 1.1.1
- [x] Node version v10.15.1
- [x] Operating System "Microsoft Windows 10 Pro"; version "10.0.18363 Build 18363"
- [x] Ace error message "Value 'visual,auditory' is invalid for 'schema:accessModeSufficient' metadata"
- [x] Input file and report: [ace-bugreport-metadata-accessmodesufficient-invalid.zip](https://github.com/daisy/ace/files/4380399/ace-bugreport-metadata-accessmodesufficient-invalid.zip)

**Comment by danielweck** [comment]
Hello, version `1.2.0-beta.7` of Ace "core" (i.e. command line tool, etc.) fixes a number of bugs (see PR https://github.com/daisy/ace/pull/314 ) related to the handling of accessibility metadata.

Could you please try the `@daisy/ace` NPM package published under the "next" tag ( see all available versions at https://www.npmjs.com/package/@daisy/ace ), which you can install from your terminal with: `npm install -g @daisy/ace@next`.

Alternatively, you may also try the "next" version of Ace by using the Ace App (GUI Graphical User Interface), just download the Linux, Windows or MacOS pre-release installer from this link https://github.com/daisy/ace-gui/releases (labelled "continuous test build")

I am closing this issue now, but feel free to reopen if you are still experiencing problems, and please provide a sample EPUB so we can reproduce the test at our end :)

Thank you!

**Comment by duenckel** [comment]
Hello @danielweck,

many thanks for the bugfix!
In version `1.2.0-beta.7` the problem does not occur anymore.
Is there already a date for a stable release of this version?

Cheers
Björn
