### ISSUE TITLE
Same code does not report the same error (nav epub:type toc not mapped to ARIA role doc-toc)

### ISSUE THREAD

**Issue by editadapt** [daisy/ace#338]
Using ACE GUI 1.1.2 on windows 10 I have this error reported: 
Minor | Best Practice | epub-type-has-matching-roleVia: aXe | nav.xhtml#epubcfi(/4/2[toc])`<nav xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="toc" id="toc">` | Element has no ARIA role matching its epub:type Ensure the element has an ARIA role matching its epub:type ARIA role should be used in addition to epub:type

Strange behaviour because it does not happens on all epub checked. Here are two document code exemples, only document 2 triggers the error in ACE: 

- in document 1 i have no violation reported by ACE, code is: 
```
 <nav epub:type="toc" id="toc">
      <h1 id="toc-title">Ariel</h1>
      <ol class="toc">
        <li id="toc-li-1">
```
- in document 2 i have violation reported by ACE, code is: 
```
<nav epub:type="toc" id="toc">
      <h1 id="toc-title">Índice</h1>
      <ol class="toc">
        <li id="toc-li-1">
```

Documents are copyrighted so i can't attach them here.

**Comment by clapierre** [comment]
looks like accented characters may be the issue here?

**Comment by editadapt** [comment]
I can confirm the error was reported on two files wich both have accented character `<h1 id="toc-title">Índice</h1>`

But i believe the error should be reported on all files (with or without accented characters).

**Comment by danielweck** [comment]
Ace App (aka "GUI") ships with Ace 2.0-beta, so the results should be equivalent when running Ace via the command line: `npm install -g @daisy/ace@next` (to install the Ace executable globally), or `npx @daisy/ace@next /PATH/TO/BOOK.EPUB` (to run it temporarily without installing it).

**Comment by danielweck** [comment]
Could you please privately share the EPUB with me? ( daniel.weck@gmail.com )
I'd like to understand the broader publication structure.

**Comment by danielweck** [comment]
Hello, I am testing the latest build of Ace which has been significantly updated. I see that the Navigation Document of `Ariel - José Enrique Rodo.epub` has `epub:type="toc"` but no `role="doc-toc"`.  This seems normal to me, if I interpret the specifications correctly (this is a "minor" ARIA best practice in the severity classification).
I see the exact same "error" in `El yo y el ello – Sigmund Freud.epub`, but there are also many more similar `epub-type-has-matching-role` errors in other XHTML publication documents (for example `epub:type=noteref` which should be accompanied with `role=doc-noteref`.
Specifications:
https://idpf.github.io/epub-guides/epub-aria-authoring/#sec-mappings
https://www.w3.org/TR/dpub-aam-1.0/#mapping_role_table
https://w3c.github.io/publ-cg/guides/aria-mapping.html#mapping-table

I am closing this issue as "fixed". Feel free to continue the discussion and / or re-open if you wish.

Ace "next" will be released shortly, I am running further tests at the moment.
See:
https://github.com/daisy/ace/pull/314
and the DAISY fork of Axe here:
https://github.com/daisy/axe-core/pull/4
