### ISSUE TITLE
"Landmark-unique" triggered for nav elements when landmarks are unique

### ISSUE THREAD

**Issue by flittle8** [daisy/ace#341]
Per discussion with @mattgarrish It looks like Ace does not recognize the DPUB-ARIA roles so is seeing all three (below) as generic navigation elements. It doesn’t matter what DPUB roles are on the nav elements, it always complains. 

One nav is identified as the toc, the other as the page list and a third as a generic nav.

Error message in Ace:

```
landmark-unique
Via: aXe
Text/toc.xhtml#epubcfi(/4/2[toc])
<nav xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="toc" id="toc" role="doc-toc"> <!--##--> <nav xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="landmarks" role="navigation"> <!--##--> <nav xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops" epub:type="page-list" role="doc-pagelist">
```

**Comment by danielweck** [comment]
Hello, I have moved this issue to the "Ace" project (which Ace App / GUI relies on). Thank you for reporting this bug. I am working on a series of related improvements and bugfixes.

**Comment by jenstroeger** [comment]
@danielweck, is it possible to add a link to the moved issue?

**Comment by danielweck** [comment]
Fixed via https://github.com/daisy/axe-core/commit/1a8dd7a516927850a44d87004ce25456c58c1404
(will be shipped shortly as part of `ace-next` which will replace Ace 1.1.1)
