### ISSUE TITLE
Add which accessibilityFeature, accessibilityHazard, etc. is invalid in the HTML report

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#343]
Ace Command Line v1.1.1
When you report 
metadata-accessibilityfeature-invalid or others like metadata-accessibilityhazard-invalid etc.

Under the details section it would be helpful to also report which item you are referring to.
ie: "resizeText" or could be a typo like "alterativeText" 

Right now you have to go through every feature to see which one is incorrect, you obviously have this information so please add it in the description to make it easier.

Thanks

**Comment by danielweck** [comment]
We are aware of several places in the report where the information could be more useful (another example: missing `role` attribute values alongside existing `epub:type` attributes, currently no hint is provided to help the user figure out the mapping)
This will be addressed in a future revision, the current development spring is a large refactoring of Ace + Axe, which will be released shortly.
https://github.com/daisy/ace/pull/314

**Comment by danielweck** [comment]
The JSON report contains the information:

https://github.com/daisy/ace/blob/b5d1b66b7008e0ad94a91341e6f5ac8d793b0e85/packages/ace-core/src/l10n/locales/en.json#L15-L20

https://github.com/daisy/ace/blob/b5d1b66b7008e0ad94a91341e6f5ac8d793b0e85/packages/ace-core/src/checker/checker-epub.js#L130-L135

**Comment by danielweck** [comment]
I checked that the HTML report contains the information too. This issue can be closed.
