### ISSUE TITLE
How to handle publications with page breaks must declare the 'dc:source' metadata when there is no other source?

### ISSUE THREAD

**Issue by CircularKen** [daisy/ace#350]
FXL EPUBs have page lists by default. So, if I create a new original work as a FXL EPUB, I have a page list but no other source to refer to and am alerted to a serious EPUB violation error in ACE.

I can enter `<dc:source>An original publication</dc:source>` but is there something better I should do?

Using Ace 1.1.3 on macOS 11.2.3.

**Comment by danielweck** [comment]
Hi Ken, I have just released v1.2.2 of Ace CLI which contains a fix for this.

GitHub:
https://github.com/daisy/ace/releases/tag/v1.2.2

NPM:
https://www.npmjs.com/package/@daisy/ace/v/latest

I will get back to you here when Ace App is ready (it will be a automated unsigned build, not an official release)

**Comment by danielweck** [comment]
CI build in progress: https://github.com/daisy/ace-gui/actions/runs/745677621

The CI artefacts will be published to: https://github.com/daisy/ace-gui/releases

**Comment by CircularKen** [comment]
> Hi Ken, I have just released v1.2.2 of Ace CLI which contains a fix for this.
> 
> GitHub:
> https://github.com/daisy/ace/releases/tag/v1.2.2
> 
> NPM:
> https://www.npmjs.com/package/@daisy/ace/v/latest
> 
> I will get back to you here when Ace App is ready (it will be a automated unsigned build, not an official release)

Thanks @danielweck. Does the fix mean that no <dc:source> will be required?

**Comment by danielweck** [comment]
Hi Ken :)

Yes, as stated in the changelog:

https://github.com/daisy/ace/blob/master/CHANGELOG.md#122-2021-04-13

Could you please try an Ace App build to confirm it works for you? Thanks you.

**Comment by CircularKen** [comment]
Hi @danielweck I am not using the CLI so will have to wait for an update to the GUI to test this…
