### ISSUE TITLE
Synchronised updating of Ace App and Ace command line 

### ISSUE THREAD

**Issue by LaZay** [daisy/ace#368]
Ace in command line is updated more frequently that Ace App.
This is a problem in our work process, as our subcontractors usually use Ace CL, when our digital PM usually prefer Ace App (most of them are not developpers).
As a matter of fact, when the last core Ace version debugs an improper error, our subcontractors do not have this error anymore  when our PM still have it in the Ace report. And they complain, or ask for an improper correction to the subcontractors.
Would it be possible to systematically deliver a new version of Ace report, when a new version of Ace core is released?
This would avoid misunderstandings between publishers and their subcontractors. Plus, it would help producing better accessible EPUBs, when using Ace App for quality control.

**Comment by LaZay** [comment]
New version of Ace APP when a new version of Ace core is released

**Comment by danielweck** [comment]
Thank you for your feedback. Good suggestion, of course.

Note that updates of the Ace "core" package are sometimes deployed with only minor changes that affect the internals of the command line interface (CLI), in which case it usually isn't necessary to release matching Ace App updates.

Also note that deploying a Ace (core / CLI) package update to NPM is a semi-automated operation that is an order of magnitude lighter than cutting a release of Ace App (GUI) for Linux, Windows, and Mac OS (i.e. 3 different operating systems / physical computers or virtual machines) which involves manually packaging, code-signing and notarising heavy build artefacts (in addition to the usual branch tagging, version updates in documentation, etc.).

That being said, there are automated "test / preview" builds of Ace App available via the release section of the GitHub website. These are not code-signed which means that Windows and MacOS users must confirm a scary security warning message when installing Ace App.

For development tracking purposes, related issues:

* https://github.com/daisy/ace/issues/362
* https://github.com/daisy/ace-gui/issues/150

**Comment by danielweck** [comment]
This is now implemented in Ace and Ace App 1.3.0
