### ISSUE TITLE
epub-pagelist-order error

### ISSUE THREAD

**Issue by ptytgat** [daisy/ace#375]
ACE 1.2.7 indicates an error  in the nav.xhtml file of our epubs, which are compliant with ACE 1.2.6
The error is generated by the rule epub-pagelist-order
I suppose that ACE 1.2.7 has more checks of <nav epub:type="page-list"> than ACE 1.2.6.
Is it possible to have informations about the evolution of this rule ?
Thanks

**Comment by danielweck** [comment]
Hello, the specification is available at this link https://www.w3.org/TR/2022/CRD-epub-a11y-11-20220607/#sec-page-list

The Ace message includes a reference to the problematic element. Use this information to find the navigation document page list hyperlink which is out of order (relative to the HTML page breaks), or to find missing page breaks which could be the result of authoring typos (e.g. misspelled HTML element id). There is also a check for page breaks that have missing page list hyperlinks, so the coverage check is complete both ways.

Please feel free to send me your EPUB so I can verify at my end: daniel.weck@gmail.com

**Comment by vincent-gros** [comment]
@ptytgat, most of the time when you see an 'epub-pagelist-order' on an ordered pagelist (I suppose this is the case based on what I know), it is because you list non-pagebreaks links.
Check your cover and titlepage to fix the issue.

**Comment by danielweck** [comment]
Fixed, see https://github.com/daisy/ace/issues/379
