### ISSUE TITLE
Is there a way to use it programatically?

### ISSUE THREAD

**Issue by michelem09** [daisy/ace#382]
I mean importing the package into an app and using it inside my own Node app without CLI or HTTP API.

**Comment by michelem09** [comment]
Well I found it, for anyone who wants to use it programatically importing packages, here is:

```
const ace = require('@daisy/ace-core');
const axeRunner = require('@daisy/ace-axe-runner-puppeteer');

const data = await ace(
  '/path/to/the/file.epub', // path
  { lang: 'en' }, // options
  axeRunner // engine
);
```

**Comment by danielweck** [comment]
That's right :)
The CLI is really just a programmatic wrapper around the exposed API:
https://github.com/daisy/ace/blob/master/packages/ace-cli/src/index.js
...with a bit of "sugar" to create an "executable":
https://github.com/daisy/ace/blob/master/packages/ace-cli/bin/ace.js

**Comment by michelem09** [comment]
Thanks! Would be great to have this in the doc too :-)
