### ISSUE TITLE
Ace Errors thrown with these accessibilityFeatures pageBreakMarkers & pageNavigation

### ISSUE THREAD

**Issue by clapierre** [daisy/ace#385]
With Ace 1.3.0
Having the following accessibilityFeatures in the OPF files cause Minor issues thrown.
```
<meta property="schema:accessibilityFeature">pageBreakMarkers</meta>
<meta property="schema:accessibilityFeature">pageNavigation</meta>
```

Results in these Warnings messages. I believe we want to support both of these values.

Minor | EPUB | metadata-accessibilityfeature-invalidVia: Ace | EPUB/content.opf | 'schema:accessibilityFeature' metadata must be set to one of the expected valuesValue 'pageBreakMarkers' is invalid for 'schema:accessibilityFeature' metadataUse one of the metadata values defined by schema.orgLearn about: Schema.org Accessibility Metadata
-- | -- | -- | -- | --
Minor | EPUB | metadata-accessibilityfeature-invalidVia: Ace | EPUB/content.opf | 'schema:accessibilityFeature' metadata must be set to one of the expected valuesValue 'pageNavigation' is invalid for 'schema:accessibilityFeature' metadataUse one of the metadata values defined by schema.orgLearn about: Schema.org Accessibility Metadata

Minor	EPUB	
metadata-accessibilityfeature-invalid

Via: Ace

EPUB/content.opf

'schema:accessibilityFeature' metadata must be set to one of the expected values
Value 'pageBreakMarkers' is invalid for 'schema:accessibilityFeature' metadata
Use one of the metadata values defined by schema.org
[Learn about: Schema.org Accessibility Metadata](https://github.com/daisy/ace/issues/new#)

Minor	EPUB	
metadata-accessibilityfeature-invalid

Via: Ace

EPUB/content.opf

'schema:accessibilityFeature' metadata must be set to one of the expected values
Value 'pageNavigation' is invalid for 'schema:accessibilityFeature' metadata
Use one of the metadata values defined by schema.org
[Learn about: Schema.org Accessibility Metadata](https://github.com/daisy/ace/issues/new#)

**Comment by danielweck** [comment]
Hi Charles, both the Ace command line tool and Ace App (GUI) are at version 1.3.2 now:

* https://www.npmjs.com/package/@daisy/ace/v/1.3.2
* https://github.com/daisy/ace-gui/releases/tag/v1.3.2

Please let me know if this releases fixes the bugs you discovered, and thank you for reporting them in the first place!

**Comment by clapierre** [comment]
Hi Daniel, not sure why this is not working but I am using the latest version of ACE 1.3.2 GUI and it still is giving this warning.

Minor | EPUB | metadata-accessibilityfeature-invalidVia: Ace | OEBPS\content.opf | 'schema:accessibilityFeature' metadata must be set to one of the expected valuesValue 'PageBreakMarkers' is invalid for 'schema:accessibilityFeature' metadataUse one of the metadata values defined by schema.org
-- | -- | -- | -- | --

Ace 1.3.2
electron 25.2.0
chrome 114.0.5735.134
note 18.15.0
v8 11.4.183.23-electron.0

**Comment by mattgarrish** [comment]
Do you actually have the value PageBreakMarkers in the work?

While we tell user agents to be lenient with case matching, the value is technically pageBreakMarkers.

**Comment by clapierre** [comment]
Ha!  @mattgarrish good eye, yup that was the problem. changing it to a lowercase 
"pageBreakMarkers" fixed the problem.
Thanks
