### ISSUE TITLE
More Explicit Command-Line Failure Descriptions

### ISSUE THREAD

**Issue by amesga** [daisy/ace#39]
If possible, add more descriptive explanations on the command line for when a file fails to pass through the Ace analysis. About half of the ePubs I have been testing fail with the error

> Unexpected error: TypeError: Cannot read property 'tocHTML' of undefined

I will continue to diagnose this error as much as I can, but so far have few leads to go on. I originally thought this was an issue in ePubs with an NCX nav file, but some NCX-based ePubs pass through Ace fine.

**Comment by marisademeglio** [comment]
So you're seeing this message on the command line (not in the browser when you open report.html)?

If there's any way you could share one of these files with us, that would help a lot! You can email it to me (marisa.demeglio@gmail.com) if you like.

**Comment by amesga** [comment]
Thanks! I just fired off an email to you. I have also described a second error where Ace never moves past the first content document. With more explanation on the command line, perhaps a cause could be tracked down.

**Comment by marisademeglio** [comment]
The cause of the errors is that the files are an unsupported format (one is EPUB 2, the other is EPUB 3 but does not validate). Leaving this issue open though because Ace should fail gracefully.
