### ISSUE TITLE
KB link for the rule "bypass" links to undefined

### ISSUE THREAD

**Issue by amesga** [daisy/ace#40]
The KB link in the Ace report for the issue "bypass" links to

> https://daisy.github.io/a11y-kb/undefined

**Comment by marisademeglio** [comment]
Some of the KB urls changed since the last release, so it'll probably be fixed in the next one. However, I can't tell from the description here exactly which issue category is affected. Could you tell me what's in the "Rule" field of the violations table for this one?

**Comment by amesga** [comment]
Sorry Marisa, the rule is "bypass". I will edit the issue description.

**Comment by rdeltour** [comment]
FWIW, this rule will be deactivated anyway in the upcoming release, since it doesn't make much sense in an EPUB.
