### ISSUE TITLE
Support for pageBreakSource property

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace#403]
We added a new [pageBreakSource property](https://www.w3.org/publishing/a11y/page-source-id/) for identifying the pagination source in EPUBs but Ace does not recognize it and emits a serious error about the source not being specified when there are page breaks.

This property replaces dc:source + source-of, although both will have to be allowed. We should prefer pageBreakSource going forward, but not sure if we want to work that into an Ace "other" message.

**Comment by danielweck** [comment]
`a11y:pageBreakSource` vs `pageBreakSource`, see inconsistent specification examples:

https://www.w3.org/publishing/a11y/page-source-id/#examples

https://www.w3.org/TR/epub-a11y-tech-11/#pageSource

**Comment by mattgarrish** [comment]
The property should not have a prefix. It is going in the meta property vocabulary to replace the source-of property.

I'll file an issue to fix the techniques.
