### ISSUE TITLE
in node, report time out on an html file  (and maybe continue)

### ISSUE THREAD

**Issue by pkra** [daisy/ace#406]
System info:

- ace 1.3.2
- node v20
- ubuntu 23.10

I have an epub file where the GUI consistently gives me a timeout error for a particularly complex html file. 

However, when running ace in node, it just hangs after a while. For node, it would be good to log something similar.

Also, it would also be great if ace could recover to continue and/or provide a (partial) report.

**Comment by danielweck** [comment]
Hi Peter, are you able to privately share the EPUB so we can repro the behaviour? This would help a lot. Thank you very much. Daniel

**Comment by pkra** [comment]
thanks @danielweck, I'll have to check.

**Comment by pkra** [comment]
"Unfortunately", I no longer have the issues with the particular book, neither with the GUI (via appimage) nor using nodejs.

I suspect I was running out of memory somewhere; I'll keep an eye out for the issue.

Again, sorry for the noise!

**Comment by zsofiamacho** [comment]
I have the same issue - the GUI gives a timeout error after 490 seconds, but the command line tool just hangs.
I will open a new ticket with the details.
