### ISSUE TITLE
HTML check error: Cannot read properties of null (reading 'toString')

### ISSUE THREAD

**Issue by mkraetke** [daisy/ace#425]
I got an strange error while validating an EPUB document. The EPUB conforms to EPUB 3.3 (checked with epubcheck 5.1.0). The EPUB file is from a customer and I cannot post it here. However, I could submit it by email under the condition of confidentiality and non-disclosure. Here is more detailed information:

- ace 1.3.2
- node 20.15.0
- windows 11 / CYGWIN_NT-10.0-22631 3.5.0-1.x86_64 2024-02-01 
- error log:
```
verbose: Converting aXe results to ace for content/XXXXXXXXXXXXX_000015.xhtml
info:    - content/XXXXXXXXXXXXX_000015.xhtml: No issues found
TypeError: Cannot read properties of null (reading 'toString')
    at C:\Users\kraetke\AppData\Roaming\npm\node_modules\@daisy\ace\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:147:93
    at Array.forEach (<anonymous>)
    at C:\Users\kraetke\AppData\Roaming\npm\node_modules\@daisy\ace\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:120:27
    at Array.forEach (<anonymous>)
    at checkSingle (C:\Users\kraetke\AppData\Roaming\npm\node_modules\@daisy\ace\node_modules\@daisy\ace-core\lib\checker\checker-chromium.js:118:48)
    at async C:\Users\kraetke\AppData\Roaming\npm\node_modules\@daisy\ace\node_modules\p-map\index.js:57:22
error:   Ace HTML check error: Failed to check Content Document 'content/XXXXXXXXXXXXX_000015.xhtml': Cannot read properties of null (reading 'toString')
error:   Ace processing error: Error: Failed to check Content Document 'content/XXXXXXXXXXXXX_000015.xhtml': Cannot read properties of null (reading 'toString')
error:   Error: Failed to check Content Document 'content/XXXXXXXXXXXXX_000015.xhtml': Cannot read properties of null (reading 'toString')
info:    Closing logs.
```

**Comment by rdeltour** [comment]
Thanks for the report Martin. Could you please send me the book by email to try and reproduce?

**Comment by danielweck** [comment]
This should be fixed via https://github.com/daisy/ace/commit/14513cfc37dbff305b5a793d8f95ef9587e3e669

...but could you please share the EPUB with me so I can investigate further? Thank you very much! :)

**Comment by mkraetke** [comment]
Thank you Daniel. I've sent you an email with a download link to the EPUB file.

**Comment by danielweck** [comment]
Hello, in your EPUB there is an SVG `image` with `href` attribute instead of `xlink:href` (relative path `images/xxxxxxx_img_cover.jpg`, ID `coverxhtml_epub-cover-svg-container`). In fact, the relative path is also incorrect, it should be `../images/xxxxxxx_img_cover.jpg`.

I implemented a workaround for the incorrect `xlink:href` XML attribute namespace, but I am afraid the broken image path must be resolved at your end (Ace doesn't crash but it cannot copy the image file into the report's folder).

**Comment by mkraetke** [comment]
Thank you. We did not produce the EPUB, however our [epub2epub](https://github.com/transpect/epub2epub converter) should repair this automatically.
