### ISSUE TITLE
Failed to generate reportes of sample ebooks 

### ISSUE THREAD

**Issue by larsvoigt** [daisy/ace#44]
Hi,
I have got some errors if I try to generate an ace report of this ebook [samplebook_v1.1_epub3_04142014.zip](https://github.com/daisy/ace/files/1349034/samplebook_v1.1_epub3_04142014.zip).
```
Error: ENOENT: no such file or directory, lstat '/tmp/tmp-14428ie8o0bumJkuI/EPUB/images/logo.jpg'
Error: ENOENT: no such file or directory, lstat '/tmp/tmp-14428ie8o0bumJkuI/EPUB/images/map-daisy-long-small.jpg'
Error: ENOENT: no such file or directory, lstat '/tmp/tmp-14428ie8o0bumJkuI/EPUB/images/map.jpg'
Error: ENOENT: no such file or directory, lstat '/tmp/tmp-14428ie8o0bumJkuI/EPUB/images/soc-small.jpg'
Error: ENOENT: no such file or directory, lstat '/tmp/tmp-14428ie8o0bumJkuI/EPUB/images/barchart-small.jpg'
etc ...
```
And also I got an error for this file [pg11-images.zip](https://github.com/daisy/ace/files/1349115/pg11-images.zip)

```
Unexpected error: TypeError: Cannot read property 'tocHTML' of undefined
```
Thanks a lot  Lars

**Comment by rdeltour** [comment]
Thank you @larsvoigt I'll have a look.

> Unexpected error: TypeError: Cannot read property 'tocHTML' of undefined

This is usually triggered on EPUB 2 books, which are currently unsupported.

**Comment by larsvoigt** [comment]
Overwhelming response time! Thank you @rdeltour...
