### ISSUE TITLE
`ace --version` fails with a Syntax Error on some setups

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#45]
Reported by Nick Williamson:

> ace --version
> 
> produced (with the directory path before npm replaced by an ellipsis)
> 
>```
> ...\npm\node_modules\ace-core\dist\report\repor```
> t-builders.js:89
>  ) {
>  ^
>SyntaxError: Unexpected token )
>   at createScript (vm.js:56:10)
>   at Object.runInThisContext (vm.js:97:10)
>   at Module._compile (module.js:542:28)
>   at Object.Module._extensions..js (module.js:579:10)
>   at Module.load (module.js:487:32)
>   at tryModuleLoad (module.js:446:12)
>   at Function.Module._load (module.js:438:3)
>   at Module.require (module.js:497:17)
>   at require (internal/module.js:20:19)
>...\npm\node_modules
>\ace-core\dist\report\axe2ace.js:5:18)

**Comment by mattgarrish** [comment]
I wasn't able to update, either.

When I run "npm update ace-core -g"  a progress bar for node 6.11.0 appears briefly and then I'm returned to the command prompt without any messages. If I run ace --version I'm still on 0.2.0

I just tried a delete and re-install and now I'm getting the same error as Nick.

I had to uninstall everything, get node 8.6.0 and reinstall to make things work. This is on Win10.

**Comment by rdeltour** [comment]
I logged the update issue as #46, it seems to be a problem with npm.
The Node compatibility issue is tracked as #47.

**Comment by clapierre** [comment]
Hello Romain With this Organic Chemistry Book from Macmillan I am getting the following err
Here is the Verbose output
Thanks


charlesl$ ace -o Organic 9781319116545_Organic_Chemistry_EPUB.epub --verbose
verbose: ACE cwd=/Users/charlesl/Documents/Consulting/Macmillan/Updated Files, outdir=Organic, tmpdir=undefined, verbose=true, silent=false, jobId=
info:    Processing 9781319116545_Organic_Chemistry_EPUB.epub
verbose: Extracting EPUB
info:    Parsing EPUB
verbose: at location '/var/folders/xp/jvwn1ll14kb4rg3jd0vh_h95pt7gkm/T/tmp-1973xI9Vb79M04r1'
info:    Analyzing accessibility metadata
debug:    dc:title=[Organic Chemistry, Structure and Function, Seventh Edition, Organic Chemistry: Structure and Function, Seventh Edition], dc:type=edupub, dc:language=en, dc:creator=[Peter Vollhardt, Neil Schore], dc:publisher=Macmillan Learning, dc:subject=Science & Mathematics, dc:rights=© 2003, 2007, 2011, and 2014 by W. H. Freeman and Company, dc:date=2017-05-22T00:00:00Z, dc:identifier=9781319116545, dc:source=9781464120275, dcterms:modified=2017-05-22T12:00:00Z, , schema:audience=schema:audience, schema:educationalUse=reading, schema:interactivityType=mixed, schema:accessMode=[textual, visual], schema:accessModeSufficient=[textual visual, textual], schema:accessibilityFeature=[tableOfContents, alternativeText, printPageNumbers, readingOrder, structuralNavigation], a11y:certifiedBy=Macmillan Learning
info:    Checking package...
info:    Checking documents...
info:    - xhtml/vol_9781464120275_cover.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_cover.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_frontendpaper.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_frontendpaper.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_htitle.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_htitle.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_author.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_author.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_title.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_title.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_copyright.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_copyright.xhtml
info:    - 0 issues found
info:    - xhtml/vol_9781464120275_brieftoc.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_brieftoc.xhtml
info:    - 26 issues found
info:    - xhtml/vol_9781464120275_toc.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_toc.xhtml
info:    - 93 issues found
info:    - xhtml/vol_9781464120275_preface.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_preface.xhtml
info:    - 9 issues found
info:    - xhtml/vol_9781464120275_ch01.xhtml
verbose: Converting aXe results to ace for xhtml/vol_9781464120275_ch01.xhtml
info:    - 3 issues found
info:    - xhtml/vol_9781464120275_ch01_01.xhtml
debug:   Error when running nightmare: "Failed to execute 'matches' on 'Element': 'm:annotation-xml' is not a valid selector."
error:   Unexpected error: Failed to check HTML content
debug:   Error: Failed to check HTML content
    at nightmare.goto.inject.inject.inject.inject.wait.axe.then.catch (/usr/local/lib/node_modules/ace-core/dist/checker/checker-nightmare.js:94:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Re-run Ace using the --verbose option to enable full debug logging.
2014-B-032:Updated Files charlesl$
