### ISSUE TITLE
Error when running nightmare

### ISSUE THREAD

**Issue by mattgarrish** [daisy/ace#48]
Not sure what to make of this: 

```
info:    - xhtml/p10.xhtml
verbose: Converting aXe results to ace for xhtml/p10.xhtml
info:    - 2 issues found
debug:   Error when running nightmare: {}
error:   Unexpected error: Failed to check HTML content
debug:   Error: Failed to check HTML content
    at nightmare.goto.inject.inject.inject.inject.wait.axe.then.catch (C:\Users\mattg_000\AppData\Roaming\npm\node_modules\ace-core\dist\checker\checker-nightmare.js:86:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I was trying to validate the cc-shared-culture book from the epub3 samples repo, which previously worked fine. I assume it's coming from p20.xhtml, but epubcheck doesn't report any problems in any case.

I don't see anything unique about those files that aren't in other epubs that I can validate.

**Comment by rdeltour** [comment]
Thanks for the report, I'll try to look into it for beta 1.

**Comment by mattgarrish** [comment]
It's some problem with the video elements in the book. If I strip them, then the message goes away.

I'll see if I can hunt down what specifically might be causing the failure.

**Comment by mattgarrish** [comment]
It looks like it chokes when an video element has source element children. If I put a src attribute on the video, then the error goes away.

The same is also true of the audio element, which is how I figured it out (it had a src attribute in that book and wasn't failing).

**Comment by rdeltour** [comment]
> It looks like it chokes when an video element has source element children

Oh. Can you paste a snippet? I thought I had some tests for that pattern.

**Comment by mattgarrish** [comment]
Here's the source video in p10.xhtml that causes the error:

```
<video id="video1" controls="controls">
    <source src="../video/shared-culture.mp4" type="video/mp4"/>
    <source src="../video/shared-culture.webm" type="video/webm"/>
    <div class="errmsg">
        <p>Your Reading System does not support (this) video.</p>
        <pre><code>
&lt;video id="video1" controls="controls"&gt;                    
&lt;source src="../video/shared-culture.mp4" type="video/mp4"/&gt;
&lt;source src="../video/shared-culture.webm" type="video/webm"/&gt;    
&lt;/video&gt;
        </code></pre>
    </div>
</video>
```

If you replace the source elements with a src attribute, leaving everything else unchanged, then no error:

```
<video id="video1" controls="controls" src="../video/shared-culture.mp4">
    <div class="errmsg">
        <p>Your Reading System does not support (this) video.</p>
        <pre><code>
&lt;video id="video1" controls="controls"&gt;                    
&lt;source src="../video/shared-culture.mp4" type="video/mp4"/&gt;
&lt;source src="../video/shared-culture.webm" type="video/webm"/&gt;    
&lt;/video&gt;
        </code></pre>
    </div>
</video>
```

The compiled epub can be downloaded here:
https://github.com/IDPF/epub3-samples/releases/download/20170606/cc-shared-culture.epub

**Comment by rdeltour** [comment]
Great, thank you Matt!
