### ISSUE TITLE
`ace-http` command doesn't install

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#51]
Installing globally `ace-core@0.3.0` installs the `ace` command but not `ace-http`.

To be investigated. Some leads:
- in any case, add a node shebang at the top of the CLI implementation
- make the file executable? (I don't think this is needed, to be verified)
- make sure multiple binaries are supported (AFAIK it is)

**Comment by marisademeglio** [comment]
Tested release 0.3.1. This command works now.
