### ISSUE TITLE
Unhandled 'error' event in 0.3.0

### ISSUE THREAD

**Issue by amesga** [daisy/ace#52]
Ace -v: 0.3.0
Node -v: 8.6.0
NPM -v: 5.3.0

Running Ace 0.3.0 on books previously validated by 0.2.0 gives the following error:

> BOML105215:~ games$ ace -o /Users/games/Documents/daisy-ace /Users/games/Downloads/9781351946841.epub 
info:    Processing /Users/games/Downloads/9781351946841.epub
events.js:182
      throw er; // Unhandled 'error' event
      ^
Error: EACCES: permission denied, open '/usr/local/lib/node_modules/ace-core/dist/ace.log'

When I navigate to the directory specified, there is no ace.log to check.

Running the command with `sudo` and `--verbose` completes but does not generate a report. Instead the following error appears:

> info:    Saving JSON report
info:    Saving HTML report
error:   Unexpected error: this.json.data.images.forEach is not a function
debug:   TypeError: this.json.data.images.forEach is not a function
    at fs.pathExists.then.then (/usr/local/lib/node_modules/ace-core/dist/report/report.js:88:35)
    at \<anonymous\>

No report is output at the specified directory. log file attached.
[ace.log](https://github.com/daisy/ace/files/1356709/ace.log)

**Comment by rdeltour** [comment]
Closing as `duplicate` since both issues are tracked elsewhere. Feel free to subscribe to the other issues to get notifications on their statuses.
