### ISSUE TITLE
review report json format

### ISSUE THREAD

**Issue by marisademeglio** [daisy/ace#55]
Make sure we're using JSON-LD properly

**Comment by marisademeglio** [comment]
posted a question to the json-ld list: https://lists.w3.org/Archives/Public/public-linked-json/2017Dec/0003.html

**Comment by mattgarrish** [comment]
Don't you just need to declare an \@vocab for all the custom properties you're using, and identify the specific properties you're pulling from elsewhere within the context:

{
  "@context":
  {
    "@vocab": "http://daisy.org/ns/ace/",
    "earl": "http://www.w3.org/ns/earl#",
    "doap": "http://usefulinc.com/ns/doap#",
    "dct": "http://purl.org/dc/terms/",
    "url": "http://schema.org/url",
    "css": "http://pending.schema.org/cssSelector"
  },
  
  "hasManifestCallbacks": "true",
  "url": "http://example.com",
  "css": "section > h2"
}

**Comment by marisademeglio** [comment]
@mattgarrish that is what we'll probably do, pending answers in the email thread linked above
