### ISSUE TITLE
Make sure absolute paths are discarded from the report?

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#64]
When building the report, Ace resolves relative paths (e.g. to EPUB’s resources like images) to absolute paths. This could be a privacy/security vulnerability, notably in a server-side scenario.

When building the final report, Ace should make sure to discard all these absolute path references.

**Comment by marisademeglio** [comment]
This would be a good option in a config file (see #77). Personally, I want the URL so I know which file I analyzed.

**Comment by marisademeglio** [comment]
Still need to relativize iframe @path properties (or get rid of and just use @src?)

**Comment by marisademeglio** [comment]
Also note that while the image.path property is omitted from the report on disk after the image has been copied, it remains in the console output if no report is saved.
