### ISSUE TITLE
New rule: `title` or `aria-label` required on page break markers

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#71]
As recommended in EPUB Accessibility Technique [PAGE-001](http://www.idpf.org/epub/a11y/techniques/techniques.html#page-001)

**Comment by clapierre** [comment]
I think this may be too strict?
If the author exposes the Page numbers to everyone, there would be no need to require an aria-label as well.

IE:  The following should be valid, but currently causes an ACE Serious Issue.

<span epub:type=“pagebreak” role=“doc-pagebreak” id=“page_1”>Page 1</span>

**Comment by rdeltour** [comment]
Thanks for the report Charles. I created a new issue.
