### ISSUE TITLE
Localisation rule description

### ISSUE THREAD

**Issue by SarahMagdalena** [daisy/ace#83]
To discuss: Should it be possible to localise axe and ace rule descriptions? We think this might increase usability for some users.

**Comment by rdeltour** [comment]
Yes, localization is definitely on our radar (after 1.0.0). I don't know if aXe supports it already, but they'd probably welcome contributions.

To be investigated, thanks for the suggestion!

**Comment by danielweck** [comment]
This was fixed in Ace `1.1.0`:
https://github.com/daisy/ace/releases

Documentation:
https://github.com/daisy/ace/wiki/Localization
