### ISSUE TITLE
page breaks not detected?

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#85]
I have page breaks in content files with that tagging:
```xml
<span epub:type="pagebreak" id="page_51" title="51"/>
```
and a page-list in nav file.

But the ace.json report says:
```json
 "properties": {
    "hasMathML": false,
    **"hasPageBreaks": false**
  },
```

**Comment by rdeltour** [comment]
sounds like a bug. I'll try to reproduce and will come back to you if I can't. Thanks!
