### ISSUE TITLE
epub-pagesource when no page breaks detected

### ISSUE THREAD

**Issue by laudrain** [daisy/ace#86]
A 'dc:source' metadata property is asked even when there are no page breaks detected.

**Comment by rdeltour** [comment]
> A 'dc:source' metadata property is asked even when there are no page breaks detected.

Doh. That would certainly be a bug. I'll try to reproduce and fix for the next release. Thanks!

**Comment by rdeltour** [comment]
@laudrain I can't reproduce this. Would you have a sample EPUB to share?

**Comment by rdeltour** [comment]
By the way, the rule (which is sadly poorly documented) is to check the a `dc:source` is provided when **page navigation** is present (like a `page-list` in the Navigation Document).

There should be another rule to check such page navigation is present when page breaks are found, but that's for another rule (not implemented yet)

/cc @mattgarrish

**Comment by rdeltour** [comment]
Removing the `bug` label and moving out of the `v0.6.0` milestone. It can be reincluded if @laudrain provides more info.

**Comment by laudrain** [comment]
@rdeltour I understand how dc:source is related to page-breaks. 
Without a nav entry of epub:type="page-list" in the nav.xhtml file, the dc:source isn't any more required. 
So I close this issue.
There is an issue about page-break detection which is #85.
