### ISSUE TITLE
Ace doesn't run on Node v4 (SyntaxError)

### ISSUE THREAD

**Issue by deborahgu** [daisy/ace#93]
I just did a fresh install. Node version is 4.2.6~dfsg-1ubuntu4.1, which is the latest Ubuntu package.
```bash
$ npm --version 
3.5.2
$ nodejs --version
v4.2.6
```
I installed with `npm install ace-core -g`.  When I run anything, I get an unexpected token error:

```
2$ ace --help
/usr/local/lib/node_modules/ace-core/dist/checker/checker.js:16
  const headings = [].concat(...results.map(docResult => docResult.outlines.headings)).filter(e => e !== undefined);
                             ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/ace-core/dist/core/ace.js:7:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

(I did look at #47 but that's reported as closed.)

**Comment by rdeltour** [comment]
thanks for the report @deborahgu.
We currently only "officially" support up to Node v6, which is the currently active LTS version (see [Node's release schedule](https://github.com/nodejs/Release#release-schedule1)).
Do you have a requirement to use Node v4?

**Comment by rdeltour** [comment]
See also [Node's guide on installing on Ubuntu](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)

**Comment by deborahgu** [comment]
no, there's no requirement to use node 4, it's just that that's what the latest apt package is.  I can switch to installing  directly.  I'll try that.  Thanks.

**Comment by marisademeglio** [comment]
@deborahgu Let us know how it goes when you've had a chance to try Ace with Node v6+ on Ubuntu!

**Comment by rdeltour** [comment]
Closing the issue. Please reopen for discussion if supporting Node v4 is critical for you!
