### ISSUE TITLE
Make sure Ace fails gracefully on SVG Content Documents

### ISSUE THREAD

**Issue by rdeltour** [daisy/ace#94]
Ace doesn't claim to be compatible with SVG Content Documents (at least for v1.0.0). We should at least make sure we fail gracefully.

**Comment by mattgarrish** [comment]
Issuing some message that documents are being skipped would be nice. I tried the sous le vent book from the samples and it runs without any message; the svg are just ignored.

Including a property in the json report that there are svg docs (embedded or in spine) would also be useful as long as they aren't being checked, as I need to indicate that minimum contrast issues still need checking, for example.
